dingo-cli/src/main/java/io/dingodb/cli/Tools.java
dingo-cli/src/main/java/io/dingodb/cli/handler/RebalanceHandler.java
dingo-cli/src/main/java/io/dingodb/cli/handler/ResourceTagHandler.java
dingo-server/src/main/java/io/dingodb/helix/HelixAccessor.java
dingo-server/src/main/java/io/dingodb/helix/rebalance/impl/LeaderFollowerResourceAssigner.java
dingo-server/src/main/java/io/dingodb/meta/helix/HelixMetaService.java
dingo-server/src/main/java/io/dingodb/server/ServerConfiguration.java

Fixed #3:When changing the tag, modify ExternalView and rebalance.

 [dingo-table-tag] Fixed #3:When changing the tag, modify ExternalView and rebalance.

---

dingokv/build.gradle
dingokv/src/main/java/io/dingodb/dingokv/metadata/Cluster.java
dingokv/src/main/java/io/dingodb/dingokv/metadata/Peer.java
dingokv/src/main/java/io/dingodb/dingokv/metadata/PeerStats.java
dingokv/src/main/java/io/dingodb/dingokv/metadata/Region.java
dingokv/src/main/java/io/dingodb/dingokv/metadata/RegionEpoch.java
dingokv/src/main/java/io/dingodb/dingokv/metadata/RegionStats.java
dingokv/src/main/java/io/dingodb/dingokv/metadata/Store.java
dingokv/src/main/java/io/dingodb/dingokv/metadata/StoreLabel.java
dingokv/src/main/java/io/dingodb/dingokv/metadata/StoreState.java
dingokv/src/main/java/io/dingodb/dingokv/metadata/StoreStats.java
dingokv/src/main/java/io/dingodb/dingokv/metadata/TimeInterval.java
dingokv/src/main/java/io/dingodb/dingokv/util/Lists.java

add metadata about dingo cluster

[dingokv] add metadata about dingo cluster

---

dingo-common/src/main/java/io/dingodb/common/config/DingoConfiguration.java

[dingo-config] read object config Fix#18

---

dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/TableMetaAdaptor.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/impl/TableMetaAdaptorImpl.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/service/CoordinatorMetaService.java

[dingo-server] fix metaservice tableKey

---

dingo-exec/src/main/java/io/dingodb/exec/impl/TaskImpl.java

fix thread pool when task run.

[dingo-exec] fix thread pool when task run.

---

dingo-calcite/src/main/java/io/dingodb/calcite/visitor/RexConverter.java
dingo-test/src/test/java/io/dingodb/test/datefuc/DateTest.java
dingo-test/src/test/java/io/dingodb/test/type/BooleanTest.java
dingo-test/src/test/resources/table-test4-support-boolean-creation.sql
dingo-test/src/test/resources/table-test4-support-boolean-insert.sql

Signed-off-by: wang.zhen <wangzhenaaa7@gmail.com>
support boolean type

[dingo-calcite] support boolean type for dingo

---

dingo-exec/src/main/java/io/dingodb/exec/operator/GetByKeysOperator.java
dingo-exec/src/main/java/io/dingodb/exec/table/PartInKvStore.java

[dingo-exec] using getValueByKey to instead of getMultiKeys

---

dingo-exec/src/main/java/io/dingodb/exec/operator/PartUpdateOperator.java
dingo-test/src/test/java/io/dingodb/test/update/UpdateTest.java
dingo-test/src/test/resources/table-update-test5-creation.sql
dingo-test/src/test/resources/table-update-test5-insert.sql

[dingo-exec] fix bug about affected rows when update

[dingo-exec] fix bug about affected rows when update

---

dingo-calcite/src/main/java/io/dingodb/calcite/visitor/DingoJobVisitor.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/RexConverter.java
dingo-exec/src/main/java/io/dingodb/exec/expr/RtExprWithType.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PartScanOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PartUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/ProjectOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/SortOperator.java
dingo-exec/src/main/java/io/dingodb/exec/sort/SortCollation.java
dingo-exec/src/main/java/io/dingodb/exec/sort/SortDirection.java
dingo-exec/src/main/java/io/dingodb/exec/sort/SortNullDirection.java
dingo-test/src/test/java/io/dingodb/test/TableWithDefaultValueTest.java
gradle.properties

Also removed dependency of Calcite in dingo-exec.

[dingo-exec] Fixed #118: Result of exprs are not correctly typed.

---

dingo-exec/src/main/java/io/dingodb/exec/operator/SortOperator.java
dingo-test/src/test/java/io/dingodb/test/limit/LimitTest.java
dingo-test/src/test/resources/table-limit-test6-creation.sql
dingo-test/src/test/resources/table-limit-test6-insert.sql

Signed-off-by: wang.zhen <wangzhenaaa7@gmail.com>
[dingo-exec] fix bug about limit

[dingo-exec] fix bug about limit

---

dingo-calcite/src/main/java/io/dingodb/calcite/func/DingoFunc.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/DingoDateNowOp.java
dingo-test/src/test/java/io/dingodb/test/datefuc/DateTest.java

Now function return string instead of timestamp.

now function return string instead

---

dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/DingoDateDateDiffOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/DingoDateDateFormatOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/timeformatmap/DateFormatUtil.java
dingo-test/src/test/java/io/dingodb/test/datefuc/DateTest.java

support various date format output.

[dingo-expr] support various date format output

---

dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/DingoDateDateDiffOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/timeformatmap/DateFormatUtil.java
dingo-test/src/test/java/io/dingodb/test/datefuc/DateTest.java

[dingo-expr] fix bug about date_format and date_diff

F date format support

---

dingo-raft-kv/src/main/java/io/dingodb/raft/kv/storage/DefaultRaftRawKVStoreStateMachine.java
dingo-raft-kv/src/main/java/io/dingodb/raft/kv/storage/RocksRawKVStore.java
dingo-raft/src/main/java/io/dingodb/raft/Node.java
dingo-raft/src/main/java/io/dingodb/raft/ReplicatorGroup.java
dingo-raft/src/main/java/io/dingodb/raft/core/FSMCallerImpl.java
dingo-raft/src/main/java/io/dingodb/raft/core/NodeImpl.java
dingo-raft/src/main/java/io/dingodb/raft/core/ReadOnlyServiceImpl.java
dingo-raft/src/main/java/io/dingodb/raft/core/Replicator.java
dingo-raft/src/main/java/io/dingodb/raft/entity/LogEntry.java
dingo-raft/src/main/java/io/dingodb/raft/error/OverloadException.java
dingo-raft/src/main/java/io/dingodb/raft/option/ApplyTaskMode.java
dingo-raft/src/main/java/io/dingodb/raft/option/NodeOptions.java
dingo-raft/src/main/java/io/dingodb/raft/storage/LogManager.java
dingo-raft/src/main/java/io/dingodb/raft/storage/impl/LogManagerImpl.java
dingo-raft/src/main/java/io/dingodb/raft/storage/impl/RocksDBLogStorage.java
dingo-raft/src/main/java/io/dingodb/raft/storage/snapshot/SnapshotExecutorImpl.java
dingo-raft/src/main/java/io/dingodb/raft/util/ThreadId.java
dingo-raft/src/main/java/io/dingodb/raft/util/Utils.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/CoordinatorServer.java
dingo-store-raft/src/main/java/io/dingodb/store/raft/RaftStoreInstance.java
dingo-store-raft/src/test/java/io/dingodb/store/raft/TestRaftStoreInstance.java
gradle.properties

[dingo-raft] lock optimize at log manager

[dingo-raft] lock optimize at log manager

---

dingo-calcite/src/main/java/io/dingodb/calcite/visitor/RexConverter.java
dingo-driver/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-expr/parser/src/main/java/io/dingodb/expr/parser/op/FunFactory.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/evaluator/base/DateEvaluator.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/evaluator/base/TimestampEvaluator.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/evaluator/type/TypeEvaluators.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/utils/DateFormatUtil.java
dingo-test/src/test/java/io/dingodb/test/datefuc/DateTest.java

[dingo-expr] support %H in date_format function, support cast, date/timestamp, date_diff

[dingo-expr] support time/datetime/date function

---

dingo-driver/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/evaluator/type/TypeEvaluators.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/DingoDateDiffOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/DingoDateFormatOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/utils/DateFormatUtil.java
dingo-test/src/test/java/io/dingodb/test/datefuc/DateTest.java

ID1000117
[dingo-0.3.0] 当日期的月按M格式，日按D格式输入时处理失败
ID1000106
[dingo-0.3.0] Date_Format函数不支持自定义字符串

[dingo-expr] support %H in date_format function, support cast 

---

dingo-driver/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/evaluator/type/TypeEvaluators.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/evaluator/utils/Time2StringUtils.java
dingo-test/src/test/java/io/dingodb/test/BasicTypeWithDateTest.java
dingo-test/src/test/java/io/dingodb/test/BasicTypeWithTimeTest.java
dingo-test/src/test/java/io/dingodb/test/datefuc/DateTest.java

1. Add convertion from java.sql.date/time/timestamp to String
2. Add convertion from Long to java.sql.date/time/timstamp

[dingo-expr] Add type convertion from java.sql.date/time/timestamp to String

---

dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/utils/DateFormatUtil.java
dingo-test/src/test/java/io/dingodb/test/datefuc/DateTest.java

fix datediff support now/current_timestamp

[dingo-expr] fix datediff support now/current_timestamp

---

dingo-common/build.gradle
dingo-common/src/main/java/io/dingodb/common/metrics/DingoMetrics.java
dingo-exec/src/main/java/io/dingodb/exec/Services.java
dingo-raft/src/main/java/io/dingodb/raft/core/FSMCallerImpl.java
gradle.properties

[dingo-common] Add metrics wrapper for JMX reporter

[dingo-common] Add metrics wrapper for JMX reporter

---

dingo-calcite/src/test/java/io/dingodb/calcite/visitor/TestRexConverter.java
dingo-net-netty/src/main/java/io/dingodb/net/netty/connection/impl/NetServiceLocalConnection.java
dingo-net-netty/src/main/java/io/dingodb/net/netty/utils/Logs.java
dingo-raft-kv/src/main/java/io/dingodb/raft/kv/storage/RocksRawKVStore.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/adaptor/impl/ColumnAdaptor.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/adaptor/impl/ReplicaAdaptor.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/adaptor/impl/TableAdaptor.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/adaptor/impl/TablePartAdaptor.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/schedule/ClusterScheduler.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/schedule/TableScheduler.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/api/TableStoreApi.java
dingo-server/protocol/src/main/java/io/dingodb/server/protocol/CommonIdConstant.java
dingo-store-raft/src/main/java/io/dingodb/store/raft/PartStateMachine.java
dingo-store-raft/src/main/java/io/dingodb/store/raft/RaftStoreInstance.java
dingo-store-raft/src/main/java/io/dingodb/store/raft/RaftStoreInstancePart.java
dingo-store-raft/src/main/java/io/dingodb/store/raft/RaftStoreService.java
dingo-store-raft/src/test/java/io/dingodb/store/raft/TestRaftInstancePart.java
dingo-test/src/test/java/io/dingodb/test/datefuc/DateTest.java

[dingo-server, dingo-store] fix assign/drop table part

[dingo-server, dingo-store] fix assign/drop table part

---

dingo-ddl/src/main/java/io/dingodb/ddl/DingoDdlExecutor.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/evaluator/type/TypeEvaluators.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/evaluator/utils/Time2StringUtils.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/DingoCurrentDateOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/DingoDateUnixTimestampOp.java
dingo-net-netty/src/main/java/io/dingodb/net/netty/NetServiceConfiguration.java
dingo-test/src/main/java/io/dingodb/example/DingoDriverExample.java

1. Hotfix bugs about current_date() when the time is before 8:00 AM
2. Hotfix bugs about duplicated columns
3. Jdbc Connection init the default host

HotFix bugs about date and duplicated columns

---

dingo-common/src/main/java/io/dingodb/common/codec/ProtostuffCodec.java
dingo-common/src/test/java/io/dingodb/common/codec/TestProtoStuffCodec.java
dingo-common/src/test/java/io/dingodb/common/codec/pojo/School.java
dingo-common/src/test/java/io/dingodb/common/codec/pojo/Student.java
dingo-dist/build.gradle
dingo-driver-client/src/main/java/io/dingodb/driver/DingoServiceImpl.java
dingo-driver-client/src/main/java/io/dingodb/driver/api/DriverProxyApi.java
dingo-example/build.gradle
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/utils/DateFormatUtil.java
dingo-net-netty/src/main/java/io/dingodb/net/netty/packet/PacketType.java
dingo-sdk/build.gradle
dingo-server/driver-proxy/src/main/java/io/dingodb/server/driver/DriverProxyService.java
dingo-test/build.gradle
gradle.properties

1. revert dingo-driver proxy using string and object mapper
2. update proto stuff to allow null values

[dingo-driver] revert driver proxy and update protostuff to allow null value

---

dingo-common/src/main/java/io/dingodb/common/config/DingoConfiguration.java
dingo-common/src/main/java/io/dingodb/common/util/ByteArrayUtils.java
dingo-raft-kv/src/main/java/io/dingodb/raft/kv/storage/ReadIndexRunner.java
dingo-raft/src/main/java/io/dingodb/raft/storage/impl/RocksDBLogStore.java
dingo-server/protocol/src/main/java/io/dingodb/server/api/MetaServiceApi.java
dingo-store-raft/src/main/java/io/dingodb/store/raft/RaftStoreInstance.java

[dingo-raft-kv] fix rocksdb log memory leak

---

dingo-calcite/src/main/java/io/dingodb/calcite/visitor/RexConverter.java
dingo-expr/parser/src/main/java/io/dingodb/expr/parser/op/AndOp.java
dingo-expr/parser/src/main/java/io/dingodb/expr/parser/op/CaseOp.java
dingo-expr/parser/src/main/java/io/dingodb/expr/parser/op/FunFactory.java
dingo-expr/parser/src/main/java/io/dingodb/expr/parser/op/IsFalseOp.java
dingo-expr/parser/src/main/java/io/dingodb/expr/parser/op/IsNotFalseOp.java
dingo-expr/parser/src/main/java/io/dingodb/expr/parser/op/IsNotTrueOp.java
dingo-expr/parser/src/main/java/io/dingodb/expr/parser/op/IsNullOp.java
dingo-expr/parser/src/main/java/io/dingodb/expr/parser/op/IsTrueOp.java
dingo-expr/parser/src/main/java/io/dingodb/expr/parser/op/OrOp.java
dingo-expr/parser/src/test/java/io/dingodb/expr/parser/parser/TestThreeValuedLogical.java
dingo-expr/parser/src/test/java/io/dingodb/expr/parser/parser/TestThreeValuedLogicalVar.java
dingo-expr/parser/src/test/java/io/dingodb/expr/parser/parser/TestWithNull.java
dingo-expr/parser/src/test/java/io/dingodb/expr/parser/parser/TestWithNullVar.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/logical/RtAndOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/logical/RtIsFalse.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/logical/RtIsNotFalse.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/logical/RtIsNotTrue.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/logical/RtIsTrue.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/logical/RtLogicalOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/logical/RtNotOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/logical/RtOrOp.java

1. Fixed three-valued logical problem.
2. Added IS TRUE, IS FALSE, etc.

[dingo-calcite, dingo-expr] Fixed #192: IS TRUE, IS FALSE support.

---

dingo-exec/src/main/java/io/dingodb/exec/operator/ReceiveOperator.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/evaluator/type/TypeEvaluators.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/DingoDateDiffOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/DingoDateFormatOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/DingoDateUnixTimestampOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/DingoTimeFormatOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/utils/DingoDateTimeUtils.java
dingo-test/src/test/java/io/dingodb/test/datefuc/InsertAndSelectDateTest.java
dingo-test/src/test/java/io/dingodb/test/datefuc/OnlySimpleDateFunctionTest.java

Signed-off-by: wang.zhen <wangzhenaaa7@gmail.com>
[dingo-expr]dingo support time/date/timestamp]

[dingo-expr] hotfix bugs about  time/date/timestamp.

---

dingo-dist/bin/start-executor.sh
dingo-dist/bin/start.sh
dingo-dist/build.gradle
docker/templates/bin/start-executor.sh

[dingo-dist] fix store not found when start executor

[dingo-dist] fix store not found when start executor

---

dingo-exec/src/main/java/io/dingodb/exec/operator/ReceiveOperator.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/evaluator/type/TypeEvaluators.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/utils/DingoDateTimeUtils.java
dingo-test/src/test/java/io/dingodb/test/datefuc/InsertAndSelectDateTest.java
dingo-test/src/test/java/io/dingodb/test/datefuc/OnlySimpleDateFunctionTest.java

add type time/date/timestamp, fix bug about time_format

[dingo-expr] add type time/date/timestamp, fix bug about time_format

---

dingo-common/src/main/java/io/dingodb/common/error/DingoException.java
dingo-driver-client/src/main/java/io/dingodb/driver/DingoServiceImpl.java
dingo-driver/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/evaluator/type/TypeEvaluators.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/exception/FailParseTime.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/DingoTimeFormatOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/utils/DingoDateTimeUtils.java
dingo-test/src/test/java/io/dingodb/test/datefuc/InsertAndSelectDateTest.java
dingo-test/src/test/java/io/dingodb/test/datefuc/OnlySimpleDateFunctionTest.java
dingo-test/src/test/java/io/dingodb/test/exception/ExceptionTest.java

[dingo-driver] process exceptions

---

dingo-common/src/main/java/io/dingodb/common/error/DingoException.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/evaluator/type/TypeEvaluators.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/DingoDateDiffOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/DingoTimeFormatOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/time/utils/DingoDateTimeUtils.java
dingo-test/src/test/java/io/dingodb/test/datefuc/OnlySimpleDateFunctionTest.java
dingo-test/src/test/java/io/dingodb/test/exception/ExceptionTest.java

[dingo-expr] time format hour part can not equal larger than 24

[dingo-expr] time format hour part can not equal larger than 24

---

dingo-raft-kv/src/main/java/io/dingodb/raft/kv/config/RocksConfigration.java
dingo-raft/src/main/java/io/dingodb/raft/closure/ReadIndexClosure.java
dingo-raft/src/main/java/io/dingodb/raft/core/FSMCallerImpl.java
dingo-raft/src/main/java/io/dingodb/raft/core/NodeImpl.java
dingo-raft/src/main/java/io/dingodb/raft/entity/LeaderChangeContext.java
dingo-store-raft/src/main/java/io/dingodb/store/raft/RaftStoreInstance.java
gradle.properties

[dingo-raft] upgrade version of rocksdb && increase timeout of read-index

[dingo-raft]  upgrade version of rocksdb &&  increase timeout of read-index

---

dingo-cli/src/main/java/io/dingodb/cli/Tools.java
dingo-common/build.gradle
dingo-common/src/main/java/io/dingodb/common/config/DingoConfiguration.java
dingo-common/src/main/java/io/dingodb/common/config/ExchangeConfiguration.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/CoordinatorServer.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/config/RaftConfiguration.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/Starter.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/config/ExecutorConfiguration.java
dingo-store-raft/src/main/java/io/dingodb/store/raft/RaftStoreInstancePart.java
dingo-store-raft/src/main/java/io/dingodb/store/raft/RaftStoreService.java
dingo-store-raft/src/main/java/io/dingodb/store/raft/config/RaftConfiguration.java
dingo-store-raft/src/main/java/io/dingodb/store/raft/config/StoreConfiguration.java
dingo-store-raft/src/test/java/io/dingodb/store/raft/TestRaftStoreInstance.java

[ding-commom, dingo-configuration] update configuration parser

[ding-commom, dingo-configuration] update configuration parser

---

.gitignore
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/RexConverter.java
dingo-common/src/main/java/io/dingodb/common/type/DingoTypeFactory.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/utils/DateTimeUtils.java
dingo-expr/runtime/src/test/java/io/dingodb/expr/runtime/utils/TestDateTimeUtils.java
dingo-test/src/test/java/io/dingodb/test/TableWithDefaultValueTest.java

[dingo-common, dingo-calcite, dingo-expr] Fixed concat with null problem

---

dingo-raft/src/main/java/io/dingodb/raft/RouteTable.java
dingo-raft/src/main/java/io/dingodb/raft/core/NodeImpl.java
dingo-raft/src/main/java/io/dingodb/raft/core/Replicator.java
dingo-raft/src/main/java/io/dingodb/raft/rpc/impl/AbstractClientService.java
dingo-raft/src/main/java/io/dingodb/raft/rpc/impl/BoltRaftRpcFactory.java
dingo-raft/src/main/java/io/dingodb/raft/rpc/impl/BoltRpcClient.java
dingo-raft/src/main/java/io/dingodb/raft/storage/impl/LogManagerImpl.java
dingo-raft/src/main/java/io/dingodb/raft/storage/snapshot/local/LocalSnapshotStorage.java
dingo-raft/src/main/java/io/dingodb/raft/util/Utils.java

[dingo-raft] merge some code from jraft 1.3.11

[dingo-raft] merge some code from jraft 1.3.11

---

dingo-dist/conf/db_rocks.ini
dingo-raft-kv/src/main/java/io/dingodb/raft/kv/storage/RocksRawKVStore.java

[dingo-raft] update rocksdb default configuration

[dingo-raft] update rocksdb default configuration

---

dingo-cli/src/main/java/io/dingodb/cli/source/Import.java
dingo-cli/src/main/java/io/dingodb/cli/source/impl/fetch/CsvFetch.java
dingo-example/src/main/java/io/dingodb/example/DingoCliExample.java
dingo-sdk/src/main/java/io/dingodb/sdk/client/DingoMapper.java
dingo-sdk/src/main/java/io/dingodb/sdk/client/DingoOpCli.java
dingo-sdk/src/main/java/io/dingodb/sdk/common/Record.java
dingo-sdk/src/main/java/io/dingodb/sdk/mappers/BooleanMapper.java
dingo-sdk/src/main/java/io/dingodb/sdk/mappers/DateMapper.java
dingo-sdk/src/main/java/io/dingodb/sdk/mappers/TimeMapper.java
dingo-sdk/src/main/java/io/dingodb/sdk/mappers/TimestampMapper.java
dingo-sdk/src/test/java/io/dingodb/sdk/TestDingoArrayType.java
dingo-sdk/src/test/java/io/dingodb/sdk/TestDingoCliOperation.java
dingo-sdk/src/test/java/io/dingodb/sdk/TestDingoCliWithConstruct.java
dingo-sdk/src/test/java/io/dingodb/sdk/TestDingoComplexType.java
dingo-sdk/src/test/java/io/dingodb/sdk/TestDingoEmbeddedType.java

- #293  Add feature to create table using annotation
- add closeConnection in the end when using dingo client

[dingo-sdk] add annotation to create table using pojo annotation

---

dingo-cli/src/main/java/io/dingodb/cli/source/Parser.java
dingo-cli/src/main/java/io/dingodb/cli/source/impl/AbstractParser.java
dingo-cli/src/main/java/io/dingodb/cli/source/impl/fetch/CsvFetch.java
dingo-cli/src/main/java/io/dingodb/cli/source/impl/fetch/JsonFetch.java
dingo-cli/src/main/java/io/dingodb/cli/source/impl/fetch/KafkaAvroFetch.java
dingo-cli/src/main/java/io/dingodb/cli/source/impl/fetch/KafkaJsonFetch.java
dingo-common/src/main/java/io/dingodb/common/type/converter/CsvConverter.java
dingo-sdk/src/main/java/io/dingodb/sdk/mappers/BooleanMapper.java
dingo-sdk/src/main/java/io/dingodb/sdk/mappers/DateMapper.java
dingo-sdk/src/main/java/io/dingodb/sdk/mappers/TimeMapper.java
dingo-sdk/src/test/java/io/dingodb/sdk/TestDingoCliOperation.java
dingo-sdk/src/test/java/io/dingodb/sdk/TestDingoCliWithConstruct.java

#304, Fix bugs about import tools from csv and json.

[dingo-cli] hotfix bugs about import from csv and json

---

dingo-driver-client/src/main/java/io/dingodb/driver/DingoServiceImpl.java
dingo-driver-client/src/main/java/io/dingodb/driver/client/DingoDriverClient.java

[dingo-drver-client] add feature about time for jdbc client

[dingo-drver-client] add feature about time for jdbc client

---

dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoPartRangeRule.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/DingoJobVisitor.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PartScanOperator.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/number/DingoNumberPowOp.java
dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/op/number/DingoNumberRoundOp.java
dingo-test/src/test/java/io/dingodb/test/QueryBetweenAndTest.java

[dingo-calcite, dingo-exec, dingo-expr] Fix bugs related to query

---

dingo-cli/src/main/java/io/dingodb/cli/source/impl/fetch/JsonFetch.java
dingo-sdk/src/main/java/io/dingodb/sdk/mappers/BooleanMapper.java

[dingo-cli,dingo-sdk] fix bugs about import using json with a space line

---

dingo-common/src/main/java/io/dingodb/common/codec/PrimitiveCodec.java
dingo-common/src/main/java/io/dingodb/common/table/DingoKeyValueCodec.java
dingo-exec/src/main/java/io/dingodb/exec/table/PartInKvStore.java
dingo-raft-kv/src/main/java/io/dingodb/raft/kv/storage/MemoryRawKVStore.java
dingo-raft-kv/src/main/java/io/dingodb/raft/kv/storage/RaftRawKVOperation.java
dingo-raft-kv/src/main/java/io/dingodb/raft/kv/storage/RaftRawKVStore.java
dingo-raft-kv/src/main/java/io/dingodb/raft/kv/storage/RawKVStore.java
dingo-raft-kv/src/main/java/io/dingodb/raft/kv/storage/RocksDBUtils.java
dingo-raft-kv/src/main/java/io/dingodb/raft/kv/storage/RocksRawKVStore.java
dingo-raft-kv/src/test/java/io/dingodb/raft/kv/storage/TestRocksRawKVStore.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/CoordinatorServer.java
dingo-store-raft/src/main/java/io/dingodb/store/raft/RaftStoreInstance.java
dingo-store-raft/src/main/java/io/dingodb/store/raft/RaftStoreInstancePart.java
dingo-store-raft/src/main/java/io/dingodb/store/raft/RaftStoreService.java
dingo-store-raft/src/test/java/io/dingodb/store/raft/TestRaftInstancePart.java

[dingo-raft, dingo-store] Add ttl feature in store

[dingo-raft, dingo-store] Add ttl feature in store

---

dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoPartRangeRule.java
dingo-driver/src/main/java/io/dingodb/driver/DingoExplainSignature.java

[dingo-driver]Modify the format of explain result and fix query bug

---

dingo-common/src/main/java/io/dingodb/common/partition/DingoPartDetail.java
dingo-common/src/main/java/io/dingodb/common/partition/DingoTablePart.java
dingo-common/src/main/java/io/dingodb/common/table/TableDefinition.java
dingo-ddl/src/main/codegen/config.fmpp
dingo-ddl/src/main/codegen/includes/parserImpls.ftl
dingo-ddl/src/main/codegen/templates/Parser.jj
dingo-ddl/src/main/java/io/dingodb/ddl/DingoDdlExecutor.java
dingo-ddl/src/main/java/org/apache/calcite/sql/ddl/DingoSqlCreateTable.java
dingo-ddl/src/main/java/org/apache/calcite/sql/ddl/DingoSqlDdlNodes.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/adaptor/impl/TableAdaptor.java
dingo-server/protocol/src/main/java/io/dingodb/server/protocol/meta/Table.java

[dingo-ddl, dingo-common, dingo-server] partition and TTL are supported when creating table

[dingo-ddl, dingo-common, dingo-server] partition and TTL are supported when creating table

---

dingo-expr/runtime/src/main/java/io/dingodb/expr/runtime/utils/DateTimeUtils.java
dingo-test/src/test/java/io/dingodb/test/time/DateTimeFunctionTest.java

Time and timestamp formatting functions support precision.

[dingo-expr-runtime]Time and timestamp formatting functions support

---

dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/core/MirrorProcessingUnit.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/storage/rocks/RocksStorage.java
dingo-store-mpu/src/main/java/io/dingodb/store/mpu/StoreConfiguration.java
dingo-store-mpu/src/main/java/io/dingodb/store/mpu/StoreInstance.java
dingo-store-mpu/src/main/java/io/dingodb/store/mpu/StoreService.java
dingo-store-mpu/src/test/java/io/dingodb/store/mpu/StoreInstanceTest.java

[dingo-store-mpu] add configuration about rocksdb

[dingo-store-mpu] add configuration about rocksdb

---

dingo-cli/build.gradle
dingo-cli/src/main/java/io/dingodb/cli/source/impl/fetch/JsonFetch.java
dingo-dist/build.gradle
dingo-mirror-processing-unit/build.gradle
dingo-raft/build.gradle
dingo-store-raft/build.gradle
dingo-store-rocksdb/build.gradle

1. Replace Rocksdb from package io.dingodb. 
2. Hotfix bugs about import Json from files
3. add dingo-store-mpu to dingo.zip

Hotfix bugs about dingo and change dependence about rocksdb

---

dingo-common/src/main/java/io/dingodb/common/store/Part.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/core/MirrorProcessingUnit.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/storage/rocks/RocksStorage.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/storage/rocks/RocksUtils.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/adaptor/impl/TableAdaptor.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/schedule/ClusterScheduler.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/schedule/processor/TableStoreProcessor.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/ExecutorServer.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/api/TableStoreApi.java
dingo-server/protocol/src/main/java/io/dingodb/server/protocol/meta/TablePart.java
dingo-store-api/src/main/java/io/dingodb/store/api/StoreService.java
dingo-store-memory/src/main/java/io/dingodb/store/memory/MemoryStoreService.java
dingo-store-mpu/src/main/java/io/dingodb/store/mpu/StoreInstance.java
dingo-store-mpu/src/main/java/io/dingodb/store/mpu/StoreService.java
dingo-store-mpu/src/main/java/io/dingodb/store/mpu/instruction/OpInstructions.java
dingo-store-mpu/src/test/java/io/dingodb/store/mpu/StoreInstanceTest.java
dingo-store-raft/src/main/java/io/dingodb/store/raft/RaftStoreService.java
dingo-store-rocksdb/src/main/java/io/dingodb/store/rocksdb/RocksStoreService.java
gradle.properties

[dingo-store-mpu] Add ttl feature in store mpu.

[dingo-store-mpu] Add ttl feature in store mpu.

---

dingo-store-rocksdb/src/main/java/io/dingodb/store/rocksdb/RocksStoreInstance.java

The use of doDeleting flag maybe wrongly reversed.
Signed-off-by: Ketor <d.ketor@gmail.com>

[dingo-store-rocksdb] Fix RocksStoreInstance::countOrDeletePart bug.

---

dingo-calcite/src/main/codegen/config.fmpp
dingo-calcite/src/main/codegen/includes/parserImpls.ftl
dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/DingoParser.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/DingoSqlCreateTable.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/DingoSqlDdlNodes.java
dingo-calcite/src/main/java/io/dingodb/calcite/utils/ParseValueUtils.java
dingo-common/src/main/java/io/dingodb/common/partition/PartitionDefinition.java
dingo-common/src/main/java/io/dingodb/common/partition/PartitionDetailDefinition.java
dingo-common/src/main/java/io/dingodb/common/table/TableDefinition.java
dingo-driver/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/api/InternalApi.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/core/Core.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/core/InstructionSyncChannel.java
dingo-net-netty/src/main/java/io/dingodb/net/netty/NetConfiguration.java
dingo-net-netty/src/main/java/io/dingodb/net/netty/NetService.java
dingo-net-netty/src/main/java/io/dingodb/net/netty/api/ApiRegistryImpl.java
dingo-server/client/src/main/java/io/dingodb/server/client/connector/impl/ServiceConnector.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/adaptor/impl/TableAdaptor.java
dingo-server/protocol/src/main/java/io/dingodb/server/protocol/meta/Table.java
dingo-store-mpu/build.gradle

1.  fix mpu can not select primary
2. fix connection not close when socket close
3. fix create table with ttl failed

[dingo-mpu, dingo-ddl] fix mpu can not select primary and fix create table with ttl failed

---

dingo-net-api/src/main/java/io/dingodb/net/NetService.java
dingo-net-netty/src/main/java/io/dingodb/net/netty/NetService.java
dingo-net-netty/src/main/java/io/dingodb/net/netty/NettyServer.java
dingo-net-netty/src/test/java/io/dingodb/net/netty/NetServiceTest.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/Starter.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/ExecutorServer.java

1. Explicit bind Host and Port in listenPort.
2. Add TCP_NODELAY for both server and client socket.
Signed-off-by: Ketor <d.ketor@gmail.com>

[dingo-net-netty] Explicit bind Host and Port in listenPort.

---

dingo-dist/bin/start-driver.sh
dingo-sdk/src/main/java/io/dingodb/sdk/auth/service/TokenAuthImpl.java
dingo-server/client/src/main/java/io/dingodb/server/client/reload/ReloadHandler.java
dingo-server/client/src/main/java/io/dingodb/server/client/user/service/UserServiceClient.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/api/UserServiceApi.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/adaptor/impl/PrivilegeAdaptor.java
docker/templates/bin/start-driver.sh

[dingo-verify] fixed bug: sdk local start failed

[dingo-verify] fixed bug: sdk local start failed

---

dingo-dist/bin/start-web.sh
dingo-driver-client/src/main/java/io/dingodb/driver/client/DingoDriverClient.java
dingo-web/build.gradle
docker/templates/bin/start.sh
docker/templates/conf/coordinator.yaml
docker/templates/conf/executor.yaml

[dingo-verify, dingo-web] fixed bug: 1. docker security config error  2. web start failed

[dingo-verify, dingo-web] fixed bug: 1. docker security config error  2. web start failed

---

dingo-calcite/src/main/codegen/includes/parserImpls.ftl
dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlDropUser.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlGrant.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlSetPassword.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlShowGrants.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-driver/host/src/main/java/io/dingodb/driver/ServerMeta.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/adaptor/impl/UserAdaptor.java
dingo-verify/src/main/java/io/dingodb/verify/auth/IdentityAuthService.java
dingo-verify/src/main/java/io/dingodb/verify/privilege/PrivilegeVerify.java

[dingo-verify] fixed bug: 1.dbever jdbc duplicate login success 2. get Tables filter by user privileges

[dingo-verify] fixed bug: 1.dbever jdbc duplicate login success 2. get Tables filter by user privileges

---

dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/api/UserServiceApi.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/adaptor/impl/PrivilegeAdaptor.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/adaptor/impl/SchemaPrivAdaptor.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/adaptor/impl/TablePrivAdaptor.java
dingo-server/protocol/src/main/java/io/dingodb/server/api/UserServiceApi.java
dingo-verify/src/main/java/io/dingodb/verify/plugin/MysqlNativePassword.java

修复问题:
1. 密码为空登录问题
2. 对不存在用户进行操作不报错问题
3. 删除用户之后权限未删除问题

[dingo-server] Fix bugs related to user privileges

---

dingo-calcite/src/main/codegen/includes/parserImpls.ftl
dingo-calcite/src/main/codegen/templates/Parser.jj
dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/DingoSqlCreateTable.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/DingoSqlDdlNodes.java
dingo-common/src/main/java/io/dingodb/common/config/DingoConfiguration.java
dingo-common/src/main/java/io/dingodb/common/config/SecurityConfiguration.java
dingo-common/src/main/java/io/dingodb/common/table/TableDefinition.java
dingo-common/src/main/java/io/dingodb/common/util/Optional.java
dingo-driver/host/src/main/java/io/dingodb/driver/ServerMeta.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/core/Core.java
dingo-net-api/src/main/java/io/dingodb/net/error/ApiTerminateException.java
dingo-net-api/src/main/java/io/dingodb/net/service/AuthService.java
dingo-net-netty/src/main/java/io/dingodb/net/netty/Connection.java
dingo-net-netty/src/main/java/io/dingodb/net/netty/api/AuthProxyApi.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/index/IndexExecutor.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/sidebar/TableInstructions.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/sidebar/TableSidebar.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/store/StoreInstance.java
dingo-verify/src/main/java/io/dingodb/verify/auth/IdentityAuthService.java
dingo-verify/src/main/java/io/dingodb/verify/auth/TokenAuthService.java
dingo-verify/src/main/java/io/dingodb/verify/privilege/PrivilegeVerify.java
dingo-verify/src/main/java/io/dingodb/verify/token/TokenManager.java

[dingo-index, dingo-calcite] add drop index api and add engine option for create table

[dingo-index, dingo-calcite] add drop index api and add engine option for create table

---

dingo-calcite/src/main/codegen/includes/parserImpls.ftl
dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/MutableSchema.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlDropIndex.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlDropUser.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlGrant.java
dingo-cli/src/main/java/io/dingodb/cli/source/Import.java
dingo-common/src/main/java/io/dingodb/common/table/TableDefinition.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-meta-api/src/main/java/io/dingodb/meta/MetaService.java
dingo-server/client/src/main/java/io/dingodb/server/client/meta/service/MetaServiceClient.java
dingo-test/meta-local/src/main/java/io/dingodb/meta/local/MetaService.java

1.  drop权限分配给用户表级别的表，删表错误
2. 删除索引
3. 给表存在的列添加索引，报错提示
4. 删除用户时 用户名带''报错
5. 修改了!indexes 显示索引的问题

[dingo-verify] 1. privilege drop for table verify failed 2. show index invalid

---

dingo-calcite/src/main/codegen/includes/parserImpls.ftl
dingo-calcite/src/main/codegen/templates/Parser.jj
dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlAlterAddIndex.java
dingo-cli/src/main/java/io/dingodb/cli/source/Import.java
dingo-driver/client/src/main/java/io/dingodb/driver/auth/service/IdentityAuthImpl.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/api/UserServiceApi.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/adaptor/impl/PrivilegeAdaptor.java
dingo-server/coordinator/src/main/java/io/dingodb/server/coordinator/meta/adaptor/impl/TablePrivAdaptor.java
dingo-server/protocol/src/main/java/io/dingodb/server/api/UserServiceApi.java
dingo-server/protocol/src/main/java/io/dingodb/server/protocol/meta/Privilege.java
dingo-test/src/main/java/io/dingodb/test/UserTestService.java
dingo-verify/src/main/java/io/dingodb/verify/auth/TokenAuthService.java
dingo-verify/src/main/java/io/dingodb/verify/service/UserService.java

1. 索引bug: create index / drop index 依赖于index权限 alter table add index: 依赖alter和index权限 ； create table( index..) 依赖于create,index权限
2. 查看不存在表索引时弹出错误
3. 规范了索引大小写问题：索引名和列名都转为大写
4. 登录成功缓存用户信息优先级调整： user @ % -> user @ host 改为 user @ host -> user@ %, 匹配用户时优先匹配具体ip的用户
5. truncate 重建表时重建索引 / 表重建后权限信息保存

[dingo-verify] 1. truncate table bug 2. create index operator based privilege:index

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-column/build.gradle
dingo-column/src/main/java/io/dingodb/strorage/column/AbstractImmutableNativeReference.java
dingo-column/src/main/java/io/dingodb/strorage/column/AbstractNativeReference.java
dingo-column/src/main/java/io/dingodb/strorage/column/ColumnBlock.java
dingo-column/src/main/java/io/dingodb/strorage/column/ColumnConstant.java
dingo-column/src/main/java/io/dingodb/strorage/column/ColumnObject.java
dingo-column/src/main/java/io/dingodb/strorage/column/ColumnStorage.java
dingo-column/src/main/java/io/dingodb/strorage/column/ColumnStorageException.java
dingo-column/src/main/java/io/dingodb/strorage/column/Environment.java
dingo-column/src/main/java/io/dingodb/strorage/column/Status.java
dingo-common/src/main/java/io/dingodb/common/CommonId.java
dingo-server/executor/build.gradle
dingo-server/executor/src/main/java/io/dingodb/server/executor/sidebar/PartitionSidebar.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/sidebar/TableSidebar.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/store/StorageFactory.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/store/column/DingoColumnStorage.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/store/column/Reader.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/store/column/TypeConvert.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/store/column/Writer.java
settings.gradle

[dingo-column] add dingo column storage.

[dingo-column] add dingo column storage.

---

dingo-server/executor/src/main/java/io/dingodb/server/executor/sidebar/TableSidebar.java

[dingo-index] fix drop index issue

---

dingo-server/executor/src/main/java/io/dingodb/server/executor/sidebar/TableSidebar.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/store/column/DingoColumnStorage.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/store/column/Reader.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/store/column/TypeConvert.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/store/column/Writer.java

[dingo-server] update store path about merge tree, fix boolean type.

[dingo-server] update store path about merge tree, fix boolean type.

---

dingo-server/executor/src/main/java/io/dingodb/server/executor/store/column/TypeConvert.java

[dingo-server] fix timestamp for column storage.

[dingo-server] fix timestamp for column storage.

---

dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/core/ControlUnit.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/core/InstructionChain.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/core/InstructionSyncChannel.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/core/InternalInstructions.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/core/VCore.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/storage/Storage.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/storage/mem/MemStorage.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/storage/rocks/RocksStorage.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/sidebar/IndexSidebar.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/sidebar/PartitionSidebar.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/sidebar/TableSidebar.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/store/column/DingoColumnStorage.java

[dingo-mpu] fix control unit close error

[dingo-mpu] fix control unit close error

---

dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/core/Sidebar.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/core/VCore.java
dingo-mirror-processing-unit/src/main/java/io/dingodb/mpu/storage/rocks/RocksStorage.java
dingo-server/client/src/main/java/io/dingodb/server/client/meta/service/MetaServiceClient.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/sidebar/TableSidebar.java
dingo-server/executor/src/main/java/io/dingodb/server/executor/store/column/DingoColumnStorage.java

[dingo-server] fix reboot index failed on async start partition

[dingo-server] fix reboot index failed on async start partition

---

dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/MysqlType.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/NativeConstants.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/command/DingoCommands.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/command/MysqlResponseHandler.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/netty/HandshakeHandler.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/netty/MysqlIdleStateHandler.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/packet/ColumnPacket.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/packet/ERRPacket.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/packet/ExecuteStatementPacket.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/packet/HandshakePacket.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/packet/MysqlPacket.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/packet/MysqlPacketFactory.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/packet/PrepareOkPacket.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/packet/PreparePacket.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/packet/QueryPacket.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/process/MessageProcess.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/util/BufferUtil.java
dingo-common/src/main/java/io/dingodb/common/mysql/MysqlByteUtil.java
dingo-common/src/main/java/io/dingodb/common/mysql/constant/ColumnStatus.java
dingo-common/src/main/java/io/dingodb/common/mysql/scope/ScopeVariables.java

1.  jdbc PrepareStatement  insert into table values(?, ?, ?)  支持
2. 支持类型包括： int, bigint, float, double, varchar,char, date, time, timestamp,   boolean

[driver-mysql] preparestatement jdbc insert

---

dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoGetByIndexRule.java
dingo-cli/driver-mysql/build.gradle
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/command/MysqlCommands.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/command/MysqlResponseHandler.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/packet/ResultSetRowPacket.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/process/MessageProcess.java
dingo-dist/build.gradle
dingo-dist/conf/executor.yaml
dingo-executor/src/main/java/io/dingodb/server/executor/Configuration.java
dingo-executor/src/main/java/io/dingodb/server/executor/Starter.java
dingo-executor/src/main/java/io/dingodb/server/executor/service/UserService.java
docker/templates/conf/executor.yaml

1主要集成了mysql启动到executor启动中，配置文件添加了相关配置

[dingo-mysql] identify authed and privilege verify

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoRootSchema.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowTableOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowVariablesOperation.java
dingo-executor/src/main/java/io/dingodb/server/executor/service/UserService.java

1.  用户登录及认证 codec问题
2.  从metaService 获取schema时统一改为大写

[dingo-verify] fix bug: authed codec

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoRangeDeleteRule.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/MysqlConnection.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/command/MysqlResponseHandler.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/netty/HandshakeHandler.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/netty/MysqlIdleStateHandler.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/process/MessageProcess.java
dingo-common/src/main/java/io/dingodb/common/table/TableDefinition.java
dingo-executor/src/main/java/io/dingodb/server/executor/common/Mapping.java
dingo-executor/src/main/java/io/dingodb/server/executor/common/TableDefinition.java
dingo-executor/src/main/java/io/dingodb/server/executor/service/UserService.java

处理问题1. delete range报错
2. jdbc创建表默认单副本
3. 创建用户登录失败提示主机错误

[fix][dingo-mysql] Fix bug:  1. delete range 2. create table replica default 1

---

dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/command/MysqlCommands.java
dingo-exec/src/main/java/io/dingodb/exec/partition/RangeStrategy.java

解决问题：
mysql 所有sql都转为小写
多分区表查询时存在空指针

[fix][dingo-mysql] Fix bug: sql -> lower

---

dingo-calcite/src/main/codegen/config.fmpp
dingo-calcite/src/main/codegen/includes/parserImpls.ftl
dingo-calcite/src/main/codegen/templates/Parser.jj
dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlAlterUser.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/IdleTimeWatcher.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/command/MysqlResponseHandler.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/netty/HandshakeHandler.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/packet/AuthPacket.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/packet/ResultSetRowPacket.java
dingo-common/src/main/java/io/dingodb/common/privilege/UserDefinition.java
dingo-executor/src/main/java/io/dingodb/server/executor/service/UserService.java
dingo-test/src/main/java/io/dingodb/test/UserTestService.java
dingo-verify/src/main/java/io/dingodb/verify/service/UserService.java

1.  创建用户时require ssl, 要求必须用ssl连接
2. 交互式客户端超时变量的应用
3. 解决了mysql客户端timeZone的问题

[feat][dingo-mysql] Support: 1.create user require ssl 2. interactive timeout 3. fix bug: timeZone

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoParser.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoRangeDeleteRule.java
dingo-common/src/main/java/io/dingodb/common/privilege/PrivilegeDict.java
dingo-dist/build.gradle
dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-mysql-init/build.gradle
dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
dingo-mysql-init/src/main/resources/table-information-global_variables.json
dingo-mysql-init/src/main/resources/table-mysql-db.json
dingo-mysql-init/src/main/resources/table-mysql-tables_priv.json
dingo-mysql-init/src/main/resources/table-mysql-user.json
gradle.properties
settings.gradle

fix bug:
1. getTables stackOverFollow
2. set password failed
3. add mysql-init module
4. range delete failed

[fix][dingo-mysql] Fix bug: jdbc getTables api stackOverFollow

---

dingo-calcite/src/main/codegen/includes/parserImpls.ftl
dingo-calcite/src/main/codegen/templates/Parser.jj
dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlAlterUser.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlCreateUser.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/SetOptionOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowDatabaseOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/runtime/DingoResource.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoStreamingConverterVisitFun.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/MysqlConnection.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/SessionVariableChangeWatcher.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/Starter.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/command/MysqlCommands.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/command/MysqlResponseHandler.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/netty/HandshakeHandler.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/netty/MysqlNettyServer.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/packet/ResultSetRowPacket.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/process/MessageProcess.java
dingo-common/src/main/java/io/dingodb/common/mysql/constant/ErrorCode.java
dingo-common/src/main/java/io/dingodb/common/privilege/UserDefinition.java
dingo-dist/conf/executor.yaml
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDdlVerify.java
dingo-driver/host/src/main/resources/io/dingodb/calcite/runtime/DingoResource_en.properties
dingo-executor/src/main/java/io/dingodb/server/executor/Starter.java
dingo-executor/src/main/java/io/dingodb/server/executor/service/UserService.java
dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
dingo-mysql-init/src/main/resources/table-mysql-tables_priv.json
docker/templates/conf/executor.yaml

1.  inner join blocking : executor authed failed
2. 挂起任务阻塞客户端登录

[fix][dingo-mysql] Fix bug: inner join blocking

---

dingo-client/src/main/java/io/dingodb/client/operation/RangeUtils.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/DeleteOperation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/DeleteRangeOperation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/GetOperation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/Operation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/PutIfAbsentOperation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/PutOperation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/ScanOperation.java
dingo-client/src/main/java/io/dingodb/client/utils/OperationUtils.java
dingo-common/src/main/java/io/dingodb/common/util/RangeUtils.java
dingo-executor/src/main/java/io/dingodb/server/executor/service/MetaService.java

[dingo-client] Fix scan validate

[dingo-client] Fix scan validate

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/DingoInitializerExpressionFactory.java
dingo-calcite/src/main/java/io/dingodb/calcite/runtime/DingoResource.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/packet/ResultSetRowPacket.java
dingo-driver/host/src/main/resources/io/dingodb/calcite/runtime/DingoResource_en.properties
dingo-verify/src/main/java/io/dingodb/verify/privilege/PrivilegeVerify.java

1.   column default invalid; 
2.   insert into table -> autofill for empty

[fix][dingo-verify] Fix bug: 1. column default invalid; 

---

dingo-calcite/src/main/java/io/dingodb/calcite/rel/DingoPartRangeDelete.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoRangeDeleteRule.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoRangeRule.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoRangeScanRule.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoRangeDeleteVisitFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoRangeScanVisitFun.java
dingo-client/src/main/java/io/dingodb/client/OperationService.java
dingo-common/src/main/java/io/dingodb/common/util/DefinitionUtils.java
dingo-exec/src/main/java/io/dingodb/exec/partition/RangeStrategy.java

[dingo-calcite] Fix check and convert range

[dingo-calcite] Fix check and convert range

---

dingo-client/src/main/java/io/dingodb/client/OperationService.java
dingo-client/src/main/java/io/dingodb/client/common/Record.java
dingo-client/src/main/java/io/dingodb/client/common/TableInfo.java
dingo-client/src/main/java/io/dingodb/client/operation/RangeUtils.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/DeleteOperation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/DeleteRangeOperation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/GetOperation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/Operation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/PutIfAbsentOperation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/PutOperation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/ScanOperation.java
dingo-client/src/main/java/io/dingodb/client/utils/OperationUtils.java

[dingo-client] Add extract values for record, fix table info cache.

[dingo-client] Add extract values for record, fix table info cache.

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/netty/HandshakeHandler.java
dingo-common/src/main/java/io/dingodb/common/CommonId.java
dingo-common/src/main/java/io/dingodb/common/mysql/MysqlByteUtil.java
dingo-common/src/main/java/io/dingodb/common/util/ByteUtils.java
dingo-executor/src/main/java/io/dingodb/server/executor/service/UserService.java
dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
dingo-mysql-init/src/main/resources/table-mysql-db.json
dingo-mysql-init/src/main/resources/table-mysql-tables_priv.json
dingo-mysql-init/src/main/resources/table-mysql-user.json

1. where in subitems exceed 20 trigger NullPointerException

[fix][dingo-mysql] Fix bug:  NullPointerException 

---

dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/command/MysqlResponseHandler.java
dingo-common/src/main/java/io/dingodb/common/CommonId.java
dingo-common/src/main/java/io/dingodb/common/util/ByteArrayUtils.java

1. ComparableByteArray  Serializer/Derializer  Exception

[fix][dingo-mysql] Fix bug: where in Exception

---

dingo-calcite/src/main/codegen/config.fmpp
dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowTableDistributionOperation.java

Fix bug: show region error after split region

[fix][dingo-calcite] Fix bug: show region error after split region

---

dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/MysqlConnection.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-executor/src/main/java/io/dingodb/server/executor/service/UserService.java

fix bug:
1. getColumns , getSchemas stackOverFollowException
2. userServuce apply for compare and set

[fix][dingo-driver] Fix bug: getSchemas StackOverFollow

---

dingo-calcite/src/main/java/io/dingodb/calcite/utils/TableUtils.java
dingo-calcite/src/test/java/io/dingodb/calcite/TestGetByKeys.java
dingo-client/build.gradle
dingo-client/src/main/java/io/dingodb/client/common/Key.java
dingo-client/src/main/java/io/dingodb/client/operation/AggregationOperator.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/CompareAndSetOperation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/KeyRangeCoprocessor.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/OpRangeCoprocessor.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/PutIfAbsentOperation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/PutOperation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/ScanCoprocessorOperation.java
dingo-client/src/main/java/io/dingodb/client/utils/OperationUtils.java
dingo-executor/src/main/java/io/dingodb/server/executor/common/AggregationOperator.java
dingo-executor/src/main/java/io/dingodb/server/executor/service/CodecService.java

[dingo-client] Fix codec schema order

[dingo-client] Fix codec schema order

---

dingo-calcite/src/main/codegen/includes/parserImpls.ftl
dingo-calcite/src/main/java/io/dingodb/calcite/DingoParser.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/dql/SqlDesc.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/dql/SqlShowColumns.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/dql/SqlShowCreateTable.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/dql/SqlShowFullTables.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowColumnsOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowCreateTableOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowFullTableOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/SqlToOperationConverter.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/packet/MysqlPacketFactory.java
dingo-common/src/main/java/io/dingodb/common/util/DefinitionUtils.java
dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
dingo-mysql-init/src/main/resources/table-information-columns.json
dingo-mysql-init/src/main/resources/table-information-events.json
dingo-mysql-init/src/main/resources/table-information-key_column_usage.json
dingo-mysql-init/src/main/resources/table-information-partitions.json
dingo-mysql-init/src/main/resources/table-information-routines.json
dingo-mysql-init/src/main/resources/table-information-statistics.json
dingo-mysql-init/src/main/resources/table-information-triggers.json

1. DBeaver use mysql jdbc connect dingo  
2. modify root password
3. show table Distribution timezone

[fix][dingo-mysql] Fix bug: DBeaver use mysql jdbc connect dingo  

---

dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/command/MysqlResponseHandler.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDdlVerify.java

[fix][dingo-mysql] Fix bug: big data query disconnect

[fix][dingo-mysql] Fix bug: big data query disconnect

---

dingo-mysql-init/src/main/resources/table-mysql-db.json
dingo-mysql-init/src/main/resources/table-mysql-tables_priv.json

modify db,tables_priv column name -> user

[fix][dingo-mysql-init] Fixed bug: modify db,tables_priv column name 

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/SetOptionOperation.java

set global wait_timeout=60 cause by jdbc connect error

[fix][dingo-calcite]  Format set variables as String

---

dingo-verify/src/main/java/io/dingodb/verify/auth/IdentityAuthService.java

[fix][dingo-verify] Error to distribute tasks

---

dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/command/MysqlCommands.java

Join query failed cause by stop executors

[fix][driver-mysql] Join query failed cause by stop executors

---

dingo-client/src/main/java/io/dingodb/client/operation/impl/DeleteRangeOperation.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PartUpdateOperator.java

[dingo-exec] Fix update return count

[dingo-exec] Fix update return count

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/runtime/DingoResource.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/command/MysqlCommands.java
dingo-cli/driver-mysql/src/main/java/io/dingodb/driver/mysql/command/MysqlResponseHandler.java
dingo-common/src/main/java/io/dingodb/common/mysql/MysqlServer.java
dingo-driver/host/src/main/resources/io/dingodb/calcite/runtime/DingoResource_en.properties

Mysql Protocol error disconnect

[fix][driver-mysql] Mysql Protocol error disconnect

---

dingo-calcite/src/main/codegen/templates/Parser.jj

fixed bug:  Connect error: mysql.connector using python

[fix][dingo-calcite] Connect error: mysql.connector using python 

---

dingo-client/src/main/java/io/dingodb/client/operation/impl/ScanCoprocessorOperation.java

[dingo-client] Use dingo schema type for scan coprocessor reduce.

[dingo-client] Use dingo schema type for scan coprocessor reduce.

---

dingo-client/src/main/java/io/dingodb/client/IndexService.java
dingo-client/src/main/java/io/dingodb/client/OperationService.java
dingo-client/src/main/java/io/dingodb/client/utils/OperationUtils.java

[dingo-client] Fix not get cause from CompletionException

[dingo-client] Fix not get cause from CompletionException

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoGetByKeysFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoLikeScanVisitFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoRangeDeleteVisitFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoRangeScanVisitFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoStreamingConverterVisitFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoValuesVisitFun.java
dingo-client/src/main/java/io/dingodb/client/common/IndexInfo.java
dingo-client/src/main/java/io/dingodb/client/common/TableInfo.java
dingo-client/src/main/java/io/dingodb/client/operation/RangeUtils.java
dingo-common/src/main/java/io/dingodb/common/ConsistentHashing.java
dingo-exec/src/main/java/io/dingodb/exec/partition/DingoPartitionStrategyFactory.java
dingo-exec/src/main/java/io/dingodb/exec/partition/HashRangeStrategy.java
dingo-exec/src/main/java/io/dingodb/exec/partition/PartitionStrategy.java

[dingo-client, dingo-exec] Add support hash range strategy

[dingo-client, dingo-exec] Add support hash range strategy

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-client/src/main/java/io/dingodb/client/common/IndexInfo.java
dingo-client/src/main/java/io/dingodb/client/common/TableInfo.java
dingo-client/src/main/java/io/dingodb/client/operation/RangeUtils.java
dingo-common/src/test/java/io/dingodb/common/partition/ConsistentHashingTest.java

[dingo-client, dingo-exec] Update the hash partition strategy code style

[dingo-client, dingo-exec] Update the hash partition strategy code style

---

dingo-dist/bin/sqlline.sh
docs/usage/how_to_use_dingodb.md

Add SqlLine client script ，usage:
./bin/sqlline host user password
example:
./bin/sqlline 172.20.3.93 root 123123

[fix][dingo-dist] Add SqlLine client script

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-client/src/main/java/io/dingodb/client/IndexOperationService.java
dingo-client/src/main/java/io/dingodb/client/OperationService.java
dingo-common/src/main/java/io/dingodb/common/util/DefinitionUtils.java
dingo-exec/src/main/java/io/dingodb/exec/partition/HashRangeStrategy.java
dingo-executor/src/main/java/io/dingodb/server/executor/common/Mapping.java
dingo-executor/src/main/java/io/dingodb/server/executor/service/MetaService.java

[dingo-client, dingo-exec] Fix hash partition strategy problem

[dingo-client, dingo-exec] Fix hash partition strategy problem

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/AnalyzeTableOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/SqlToOperationConverter.java
dingo-calcite/src/main/java/io/dingodb/calcite/stats/AnalyzeInfo.java
dingo-calcite/src/main/java/io/dingodb/calcite/stats/StatsOperator.java
dingo-calcite/src/main/java/io/dingodb/calcite/stats/StatsTaskState.java
dingo-calcite/src/main/java/io/dingodb/calcite/stats/task/AnalyzeTask.java
dingo-calcite/src/main/java/io/dingodb/calcite/stats/task/RefreshStatsTask.java
dingo-executor/src/main/java/io/dingodb/server/executor/Starter.java
dingo-executor/src/main/java/io/dingodb/server/executor/schedule/SchedulerService.java
dingo-executor/src/main/java/io/dingodb/server/executor/schedule/stats/AnalyzeScanTask.java
dingo-executor/src/main/java/io/dingodb/server/executor/schedule/stats/TableModifyMonitorTask.java
dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
dingo-mysql-init/src/main/resources/mysql-analyzeTask.json
dingo-scheduler-api/src/main/java/io/dingodb/scheduler/SchedulerService.java

Auto trigger analyze by schedule

[feature][dingo-calcite] Auto trigger analyze by schedule

---

dingo-calcite/src/main/java/io/dingodb/calcite/meta/DingoCostModel.java
dingo-calcite/src/main/java/io/dingodb/calcite/meta/DingoCostModelV1.java
dingo-calcite/src/main/java/io/dingodb/calcite/meta/DingoRelMdCost.java
dingo-calcite/src/main/java/io/dingodb/calcite/rel/DingoGetByIndexMerge.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoGetByIndexRule.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoVectorIndexRule.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/DingoJobVisitor.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/DingoRelVisitor.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoGetByIndexMergeVisitFun.java
dingo-common/src/main/java/io/dingodb/common/mysql/DingoArray.java
dingo-common/src/main/java/io/dingodb/common/mysql/constant/ColumnType.java
dingo-driver/client/src/main/java/org/apache/calcite/avatica/util/DingoAccessor.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/command/MysqlResponseHandler.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/packet/PrepareResultSetRowPacket.java
dingo-exec/src/main/java/io/dingodb/exec/operator/IndexMergeOperator.java

1. fix bug: mysql client show array null   -> array show by type string
2. add index merge

[fix][dingo-calcite] Mysql Client show array null

---

dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoRangeDeleteRule.java

[dingo-exec] Optimize delete of full table data

[dingo-exec] Optimize delete of full table data

---

dingo-calcite/src/main/codegen/includes/parserImpls.ftl
dingo-common/src/main/java/io/dingodb/common/type/scalar/LongType.java
dingo-exec/src/main/java/io/dingodb/exec/table/PartInKvStore.java
dingo-executor/src/main/java/io/dingodb/server/executor/common/TableDefinition.java
dingo-store-proxy/src/main/java/io/dingodb/store/service/StoreService.java

  修复问题：
1. bigint类型过滤查询失败
2. 日期类型作为索引字段插入数据失败
3. 建表空指针问题以及分区语法完善
4. 更新数据返回的affected rows不对

[dingo-calcite, dingo-executor] Fix index related bugs

---

dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/command/MysqlResponseHandler.java

[fix][mysql-service] Array show error

---

dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoGetVectorByDistanceVisitFun.java
dingo-common/src/main/java/io/dingodb/common/mysql/DingoArray.java
dingo-exec/build.gradle
dingo-exec/src/main/java/io/dingodb/exec/channel/ReceiveEndpoint.java
dingo-exec/src/main/java/io/dingodb/exec/operator/VectorPointDistanceOperator.java
dingo-executor/build.gradle
dingo-store-api/src/main/java/io/dingodb/store/api/StoreInstance.java
dingo-store-proxy/src/main/java/io/dingodb/store/common/Mapping.java
dingo-store-proxy/src/main/java/io/dingodb/store/service/StoreService.java
dingo-tool-api/build.gradle
dingo-tool-api/src/main/java/io/dingodb/tool/api/ToolService.java
dingo-tool-api/src/main/java/io/dingodb/tool/api/ToolServiceProvider.java
dingo-tool-service/build.gradle
dingo-tool-service/src/main/java/io/dingodb/tool/service/ToolService.java
settings.gradle

1. Calculate distance invoke by toolservice
2. DingoArray override method toString

[fix][dingo-exec] Calculate distance invoke by toolservice

---

dingo-client/build.gradle

[dingo-exec] Fix publish package error

[dingo-exec] Fix publish package error

---

dingo-exec/src/main/java/io/dingodb/exec/fun/vector/VectorL2DistanceFun.java
dingo-exec/src/main/java/io/dingodb/exec/restful/RestfulConnection.java
dingo-exec/src/main/java/io/dingodb/exec/restful/RestfulRequest.java
dingo-exec/src/main/java/io/dingodb/exec/restful/VectorExtract.java

Modify vector extract function

[fix][dingo-exec] Modify vector extract function

---

dingo-common/src/main/java/io/dingodb/common/mysql/DingoArray.java
dingo-common/src/main/java/io/dingodb/common/util/Utils.java
dingo-driver/client/src/main/java/io/dingodb/driver/DingoClientResultSet.java
dingo-driver/client/src/main/java/org/apache/calcite/avatica/util/DingoAccessor.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/command/MysqlResponseHandler.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/packet/PrepareResultSetRowPacket.java

1.  array 元素类型为time, date, timestamp， 显示时间比实际多8个小时

[fix][dingo-driver] Array type time show error

---

dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoRules.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoVectorIndexRule.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoVectorJoinRule.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoGetByIndexMergeVisitFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoGetByIndexVisitFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoGetVectorByDistanceVisitFun.java
dingo-common/src/main/java/io/dingodb/common/util/Utils.java
dingo-driver/client/src/main/java/io/dingodb/driver/DingoClientResultSet.java
dingo-exec/src/main/java/io/dingodb/exec/converter/JsonConverter.java

1. Vector pre query null:   InSubQueryThreshold > 20
2. index hash query NullPointException

[fix][dingo-calcite] Vector pre query null

---

dingo-driver/client/src/main/java/org/apache/calcite/avatica/util/DingoAccessor.java

[fix][dingo-driver] Float array init error

---

dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoTableScanVisitFun.java
dingo-partition-base/src/main/java/io/dingodb/partition/base/HashRangePartitionService.java

[dingo-exec] Fix hash partition calculation partitionpange problem

[dingo-exec] Fix hash partition calculation partitionpange problem

---

dingo-calcite/src/main/java/io/dingodb/calcite/fun/DingoInferTypes.java
dingo-calcite/src/main/java/io/dingodb/calcite/fun/DingoOperatorTable.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoVectorIndexRule.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoVectorVisitFun.java
dingo-exec/src/main/java/io/dingodb/exec/fun/vector/VectorImageFun.java
dingo-exec/src/main/java/io/dingodb/exec/fun/vector/VectorTextFun.java
dingo-exec/src/main/java/io/dingodb/exec/restful/RestfulRequest.java
dingo-exec/src/main/java/io/dingodb/exec/restful/VectorExtract.java

[fix][dingo-calcite] Add image vector function

---

dingo-calcite/src/main/java/io/dingodb/calcite/stats/StatsOperator.java
dingo-exec/src/main/java/io/dingodb/exec/restful/VectorExtract.java
dingo-executor/src/main/java/io/dingodb/server/executor/service/UserService.java
dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
dingo-tool-service/src/main/java/io/dingodb/tool/service/ToolService.java

store,coordinator schema 改为大写，sql修改

[fix][dingo-calcite] Use uppercase letter to name internal schema

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/DingoParser.java
dingo-calcite/src/main/java/io/dingodb/calcite/rel/LogicalDingoTableScan.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoGetByIndexRule.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoModifyIndexRule.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoRules.java
dingo-calcite/src/main/java/io/dingodb/calcite/runtime/DingoResource.java
dingo-calcite/src/main/java/io/dingodb/calcite/schema/DingoSchema.java
dingo-common/src/main/java/io/dingodb/common/mysql/DingoArray.java
dingo-driver/client/src/main/java/org/apache/calcite/avatica/util/DingoAccessor.java
dingo-driver/host/src/main/resources/io/dingodb/calcite/runtime/DingoResource_en.properties
dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java

[fix][dingo-calcite] Drop not exists table causing a null pointer

---

dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java

[fix][dingo-mysql-init] Mysql init code error

---

dingo-driver/client/src/main/java/org/apache/calcite/avatica/util/DingoAccessor.java

[fix][dingo-driver] Array float show same val

---

dingo-test/src/test/java/io/dingodb/test/ShowTest.java

[dingo-exec] Fix showtable test problem

[dingo-exec] Fix showtable test problem

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowTableDistributionOperation.java

[dingo-exec] Fix show table hash distribution value content

[dingo-exec] Fix show table hash distribution value content

---

dingo-calcite/src/main/java/io/dingodb/calcite/fun/DingoOperatorTable.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/netty/MysqlIdleStateHandler.java
dingo-exec/src/main/java/io/dingodb/exec/fun/DingoFunFactory.java
dingo-exec/src/main/java/io/dingodb/exec/fun/mysql/VersionFun.java

[feature][dingo-driver] Add version function

---

dingo-driver/client/src/main/java/io/dingodb/driver/client/DingoDriverClient.java

[fix][driver-client] The client is not compatible with multiple different drivers

---

dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/netty/HandshakeHandler.java

Modify show variables count less than 10

[fix][mysql-service] Modify show variables count less than 10

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java

[fix][dingo-calcite] Truncate index table error

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoCoalesce.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoStreamingConverterVisitFun.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/netty/HandshakeHandler.java

[fix][dingo] Fixed some bugs

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoRelOptTable.java
dingo-calcite/src/main/java/io/dingodb/calcite/DingoTable.java
dingo-calcite/src/main/java/io/dingodb/calcite/traits/DingoRelPartitionByTable.java

Fix table in traits not refresh when recreate table.

[dingo-calcite] Fix table in traits not refresh when recreate table.

---

dingo-calcite/src/main/codegen/includes/parserImpls.ftl
dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/runtime/DingoResource.java
dingo-calcite/src/main/java/io/dingodb/calcite/schema/DingoRootSchema.java
dingo-client/src/main/java/io/dingodb/client/common/VectorCoprocessor.java
dingo-client/src/main/java/io/dingodb/client/operation/Coprocessor.java
dingo-common/src/main/java/io/dingodb/common/Coprocessor.java
dingo-common/src/main/java/io/dingodb/common/util/ByteArrayUtils.java
dingo-mysql-init/build.gradle
dingo-store-proxy/src/main/java/io/dingodb/store/common/TableDefinition.java
dingo-store-proxy/src/main/java/io/dingodb/store/service/CodecService.java
dingo-store-proxy/src/main/java/io/dingodb/store/service/MetaService.java
dingo-web/src/main/java/io/dingodb/web/utils/Conversion.java

Sync namespace byte of sdk codec and  add create/drop schema/database

[dingo-store, dingo-calcite] Sync namespace byte of sdk codec and  add create/drop schema/database

---

dingo-calcite/src/main/codegen/config.fmpp
dingo-calcite/src/main/codegen/includes/Show.ftl
dingo-calcite/src/main/codegen/includes/Transaction.ftl
dingo-calcite/src/main/codegen/templates/Parser.jj
dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/DingoParser.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlBeginTx.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlBlock.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlEnd.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlLock.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlLockBlock.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlLockTable.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlUnLock.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlUnLockBlock.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlUnLockTable.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/dql/SqlShowLocks.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/CommitTxOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/RollbackTxOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/SetOptionOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/SqlToOperationConverter.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/StartTransactionOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/VariableValidator.java
dingo-calcite/src/main/java/io/dingodb/calcite/runtime/DingoResource.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-driver/host/src/main/resources/io/dingodb/calcite/runtime/DingoResource_en.properties
dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java

[feature][dingo-calcite] Transaction syntax

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoParser.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlLockBlock.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlUnLockBlock.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/LockBlockOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/LockTableOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/SqlToOperationConverter.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/UnlockBlockOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/UnlockTableOperation.java

Add lock operation for transaction

[fix][dingo-calcite] Add lock operation for transaction

---

dingo-web/src/main/java/io/dingodb/web/utils/Conversion.java

Fix grpc cannot return null, use has field method

[dingo-web] Fix grpc cannot return null, use has field method

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/DingoParser.java
dingo-common/src/main/java/io/dingodb/common/mysql/MysqlServer.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java

1. 处理隐藏列的问题
2. 创建表字段中包含中文会导致连接中断
3. 插入数据和表字段数不符不能插入成功

[fix][dingo-calcite] InsertSubsetColumnsAllowed set false

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/DingoParser.java
dingo-calcite/src/main/java/io/dingodb/calcite/runtime/DingoResource.java
dingo-dist/bin/start-proxy.sh
dingo-driver/host/src/main/resources/io/dingodb/calcite/runtime/DingoResource_en.properties
dingo-proxy/build.gradle

1. add start-proxy.sh
2. Connection interrupted when table fields have Chinese characters

[fix][dingo-dist] Add start-proxy.sh

---

dingo-client/src/main/java/io/dingodb/client/IndexService.java
dingo-client/src/main/java/io/dingodb/client/OperationContext.java
dingo-client/src/main/java/io/dingodb/client/OperationService.java
dingo-client/src/main/java/io/dingodb/client/common/VectorSearchParameter.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/Operation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/VectorCountOperation.java
dingo-client/src/main/java/io/dingodb/client/operation/impl/VectorSearchOperation.java
dingo-proxy/src/main/java/io/dingodb/proxy/utils/Conversion.java

[dingo-client] Fix retry count result not use new instance

[dingo-client] Fix retry count result not use new instance

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java

Modify SqlCreateSchema to custom type

[fix][dingo-calcite] Modify SqlCreateSchema to custom type

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoParser.java

[fix][dingo-calcite] Json format line break escape for 0.7.1

---

dingo-calcite/src/main/codegen/includes/parserImpls.ftl
dingo-calcite/src/main/java/io/dingodb/calcite/DingoParserContext.java
dingo-calcite/src/main/java/io/dingodb/calcite/rel/AutoIncrementShuttle.java
dingo-calcite/src/test/java/io/dingodb/calcite/TestCreateTable.java

[fix][dingo-calcite] Fix create syntax error

---

dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoRules.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/SubQueryRemoveRule.java
dingo-calcite/src/main/java/io/dingodb/calcite/stats/SelectivityEstimator.java

[feature][dingo-calcite] Support subquery

---

dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
gradle.properties

[fix][dingo] Modify version to 0.7.1 

---

dingo-client/src/main/java/io/dingodb/client/IndexService.java
dingo-executor/src/main/java/io/dingodb/server/executor/schedule/SchedulerService.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/StoreService.java

[dingo-store] Fix vector table data use builder and use new lock service

[dingo-store] Fix vector table data use builder and use new lock service

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoSqlToRelConverter.java
dingo-calcite/src/main/java/io/dingodb/calcite/rel/AutoIncrementShuttle.java
dingo-calcite/src/main/java/io/dingodb/calcite/rel/DingoValues.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/MysqlConnection.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/netty/HandshakeHandler.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/netty/MysqlNettyServer.java
dingo-meta-api/src/main/java/io/dingodb/meta/MetaService.java
dingo-store-proxy/src/main/java/io/dingodb/store/service/AutoIncrementService.java
dingo-store-proxy/src/main/java/io/dingodb/store/service/MetaService.java
dingo-test/meta-local/src/main/java/io/dingodb/meta/local/LocalMetaService.java

Update autoincrement id by table

[fix][dingo-calcite] Update InSubqueryThreshold value

---

dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/StoreService.java

[fix][dingo-executor] Vector index error reporting issue

[fix][dingo-executor] Vector index error reporting issue

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/SetOptionOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowLocksOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/SqlToOperationConverter.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/VariableValidator.java
dingo-calcite/src/main/java/io/dingodb/calcite/rel/AutoIncrementShuttle.java
dingo-calcite/src/main/java/io/dingodb/calcite/rel/DingoValues.java
dingo-calcite/src/main/java/io/dingodb/calcite/runtime/DingoResource.java
dingo-common/src/main/java/io/dingodb/common/mysql/scope/ScopeVariables.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoPreparedStatement.java
dingo-driver/host/src/main/resources/io/dingodb/calcite/runtime/DingoResource_en.properties
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/MysqlConnection.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/command/MysqlCommands.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/command/MysqlResponseHandler.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/netty/HandshakeHandler.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/netty/MysqlNettyServer.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/packet/MysqlPacketFactory.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/packet/OKPacket.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/util/BufferUtil.java
dingo-exec/src/main/java/io/dingodb/exec/fun/AutoIncrementFun.java
dingo-meta-api/src/main/java/io/dingodb/meta/MetaService.java
dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/meta/MetaService.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/AutoIncrementService.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/MetaService.java
dingo-test/meta-local/src/main/java/io/dingodb/meta/local/LocalMetaService.java

Support longblob and autoincrement value is negative cause error

[fix][mysql-service] Support longblob and autoincrement value is negative cause error

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoParserContext.java
dingo-common/src/main/java/io/dingodb/common/mysql/constant/ColumnType.java
dingo-common/src/main/java/io/dingodb/common/type/DingoTypeFactory.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoPreparedStatement.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/command/MysqlCommands.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/command/MysqlResponseHandler.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/netty/HandshakeHandler.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/packet/ExecuteStatementPacket.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/packet/MysqlPacketFactory.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/packet/OKPacket.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/packet/PrepareResultSetRowPacket.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/packet/ResetStatementPacket.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/packet/SendBlobPacket.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/process/MessageProcess.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/util/BufferUtil.java

1. Support blob type
2. autoincrement too large error

[feature][mysql-service] Support blob type for 0.7.1

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/SetOptionOperation.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoConnection.java

Add onetime txisolation for transaction

[fix][dingo-calcite] Add onetime txisolation for transaction

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/SqlToOperationConverter.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoConnection.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/base/BaseTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/CommitOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/RollBackOperator.java

[fix][dingo-executor] Global autocommit variable settings issue

[fix][dingo-executor] Global autocommit variable settings issue

---

dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockDeleteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartDeleteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartUpdateOperator.java

[dingo-executor] Fix pessimistic transaction primary lock issue

[dingo-executor] Fix pessimistic transaction primary lock issue

---

dingo-exec/src/main/java/io/dingodb/exec/transaction/base/BaseTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/base/TransactionConfig.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/PessimisticRollBackOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/RollBackOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/params/RollBackParam.java
dingo-store-api/src/main/java/io/dingodb/store/api/transaction/data/TxnVariables.java

[dingo-executor] Fix pessimistic transaction rollback issue

[dingo-executor] Fix pessimistic transaction rollback issue

---

dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoPreparedStatement.java
dingo-exec/src/main/java/io/dingodb/exec/base/Job.java
dingo-exec/src/main/java/io/dingodb/exec/base/Task.java
dingo-exec/src/main/java/io/dingodb/exec/dag/Vertex.java
dingo-exec/src/main/java/io/dingodb/exec/impl/JobImpl.java
dingo-exec/src/main/java/io/dingodb/exec/impl/TaskImpl.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/AbstractParams.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/TxnPartModifyParam.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/TxnPartRangeScanParam.java

[dingo-executor] Fix batch execute transaction are not committed issue

[dingo-executor] Fix batch execute transaction are not committed issue

---

dingo-calcite/src/main/java/io/dingodb/calcite/visitor/DingoJobVisitor.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoGetByKeysFun.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoPreparedStatement.java
dingo-exec/src/main/java/io/dingodb/exec/OperatorFactory.java
dingo-exec/src/main/java/io/dingodb/exec/base/Task.java
dingo-exec/src/main/java/io/dingodb/exec/impl/JobImpl.java
dingo-exec/src/main/java/io/dingodb/exec/impl/TaskImpl.java
dingo-exec/src/main/java/io/dingodb/exec/operator/CalcDistributionOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnGetByKeysOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartRangeScanOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/AbstractParams.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/TxnGetByKeysParam.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/TxnPartRangeScanParam.java
dingo-exec/src/main/java/io/dingodb/exec/utils/OperatorCodeUtils.java
dingo-store-local/src/main/java/io/dingodb/store/local/StoreInstance.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/TransactionStoreInstance.java

[dingo-executor] Fix inaccurate data query in transactions

[dingo-executor] Fix inaccurate data query in transactions

---

dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoTableScanVisitFun.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoPreparedStatement.java
dingo-exec/src/main/java/io/dingodb/exec/base/Job.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PartRangeScanOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/ScanWithRelOpOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnGetByKeysOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/TxnGetByKeysParam.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/util/TransactionCacheToMutation.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/visitor/function/DingoPessimisticRollBackScanVisitFun.java
dingo-store-local/src/main/java/io/dingodb/store/local/StoreInstance.java

[dingo-executor] Fix prepare execute change txnId issue

[dingo-executor] Fix prepare execute change txnId issue

---

dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/base/BaseTransaction.java

[dingo-executor] Fix using blob type in prepare transaction issue

[dingo-executor] Fix using blob type in prepare transaction issue

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoParserContext.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartVectorOperator.java
dingo-web/src/main/java/io/dingodb/web/model/vo/Column.java
dingo-web/src/main/java/io/dingodb/web/service/MonitorServerService.java

Modify web monitor alarm and vector txn lookup error

[fix][dingo-web] Modify web monitor alarm and vector txn lookup error

---

dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoGetByKeysFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoScanWithRelOpVisitFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoTableScanVisitFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoVectorVisitFun.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/TxnPartVectorParam.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/TransactionStoreInstance.java

[dingo-executor] Fix some issues about pessimistic transaction

[dingo-executor] Fix some issues about pessimistic transaction

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/TxnImportDataOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/DingoJobVisitor.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoRangeDeleteVisitFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoScanWithRelOpVisitFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoTableScanVisitFun.java
dingo-exec/src/main/java/io/dingodb/exec/operator/DistributeOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockDeleteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/base/BaseTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/NoneTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/OptimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/PessimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/CommitOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/PessimisticRollBackOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/PreWriteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/RollBackOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/util/TransactionUtil.java
dingo-store-api/src/main/java/io/dingodb/store/api/transaction/exception/RegionSplitException.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/TransactionStoreInstance.java

[dingo-executor] Fix index data rollback not using indexService issue

[dingo-executor] Fix index data rollback not using indexService issue

---

dingo-driver/host/src/main/java/io/dingodb/driver/DingoConnection.java

[dingo-executor] Fix autocommit using txn mode issue

[dingo-executor] Fix autocommit using txn mode issue

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/VariableValidator.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoGetByKeysFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoVectorVisitFun.java
dingo-calcite/src/main/java/org/apache/calcite/sql2rel/SqlCosineSimilarityOperator.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/netty/MysqlNettyServer.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/packet/MysqlPacketFactory.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/process/MessageProcess.java
dingo-exec/src/main/java/io/dingodb/exec/base/JobManager.java
dingo-exec/src/main/java/io/dingodb/exec/impl/JobImpl.java
dingo-exec/src/main/java/io/dingodb/exec/impl/JobManagerImpl.java
dingo-exec/src/main/java/io/dingodb/exec/impl/TaskImpl.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartVectorOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/TxnPartVectorParam.java
dingo-exec/src/test/java/io/dingodb/exec/impl/TestTaskImpl.java
dingo-meta-api/src/main/java/io/dingodb/meta/TableStatistic.java
dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/meta/MetaService.java

1.Get table commit error
2. max_execution_time

[fix][dingo-calcite] Get table commit error

---

dingo-calcite/src/main/java/io/dingodb/calcite/meta/DingoCostModelV1.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/VariableValidator.java
dingo-calcite/src/main/java/io/dingodb/calcite/rel/LogicalDingoTableScan.java
dingo-calcite/src/main/java/io/dingodb/calcite/rel/dingo/DingoRelOp.java
dingo-calcite/src/main/java/io/dingodb/calcite/rel/dingo/DingoScanWithRelOp.java
dingo-calcite/src/main/java/io/dingodb/calcite/stats/StatsCache.java

Modify DingoScanWithRelOp getRowCount

[fix][dingo-calcite] Modify DingoScanWithRelOp getRowCount

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowCallsOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/SqlToOperationConverter.java
dingo-common/src/main/java/io/dingodb/common/mysql/scope/ScopeVariables.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-exec/src/main/java/io/dingodb/exec/operator/InfoSchemaScanOperator.java

Autoincrement return key error

[fix][dingo-calcite] Autoincrement return key error

---

dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoGetByKeysFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoTableModifyVisitFun.java
dingo-client/src/main/java/io/dingodb/client/OperationServiceV2.java
dingo-common/src/main/java/io/dingodb/common/CommonId.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-exec/src/main/java/io/dingodb/exec/OperatorFactory.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnGetByKeysOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartDeleteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnScanOperatorBase.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/AbstractParams.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/PessimisticLockParam.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/TxnGetByKeysParam.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/base/BaseTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/base/ITransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/NoneTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/OptimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/PessimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/TransactionCache.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/CleanCacheOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/params/CleanCacheParam.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/params/ScanCleanCacheParam.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/visitor/function/DingoCleanCacheVisitFun.java
dingo-exec/src/main/java/io/dingodb/exec/utils/OperatorCodeUtils.java
dingo-store-api/src/main/java/io/dingodb/store/api/transaction/data/Op.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/TransactionStoreInstance.java

[dingo-executor] Fix pessimistic transaction locking issues

[dingo-executor] Fix pessimistic transaction locking issues

---

dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnGetByKeysOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartDeleteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartUpdateOperator.java

[dingo-executor] Fix pessimistic transaction update operator issues

[dingo-executor] Fix pessimistic transaction update operator issues

---

dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartDeleteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartUpdateOperator.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/TransactionStoreInstance.java

[dingo-executor] Fix pessimistic transaction index insert issues

[dingo-executor] Fix pessimistic transaction index insert issues

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoParser.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/TxnImportDataOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/rel/DingoExportData.java
dingo-calcite/src/main/java/io/dingodb/calcite/rel/LogicalExportData.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoExportDataRule.java
dingo-calcite/src/main/java/io/dingodb/calcite/runtime/DingoResource.java
dingo-calcite/src/main/java/io/dingodb/calcite/utils/ParseValueUtils.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoExportDataVisitFun.java
dingo-calcite/src/main/java/org/apache/calcite/sql/type/SqlAppointReturnTypeInference.java
dingo-calcite/src/main/java/org/apache/calcite/sql2rel/SqlIPDistanceOperator.java
dingo-calcite/src/main/java/org/apache/calcite/sql2rel/SqlL2DistanceOperator.java
dingo-common/src/main/java/io/dingodb/common/mysql/util/DataTimeUtils.java
dingo-driver/host/src/main/resources/io/dingodb/calcite/runtime/DingoResource_en.properties
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/command/MysqlCommands.java
dingo-exec/src/main/java/io/dingodb/exec/operator/ExportDataOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartVectorOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/ExportDataParam.java

[fix][dingo-calcite] Export data time zone error

---

dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/PessimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/PessimisticRollBackOperator.java

[dingo-executor] Fix pessimistic transaction repeat update issues

[dingo-executor] Fix pessimistic transaction repeat update issues

---

dingo-proxy/build.gradle
dingo-web/build.gradle
gradle.properties

Fix security scanning vulnerabilities

[fix][gradle] Fix security scanning vulnerabilities for 0.7.1

---

dingo-exec/src/main/java/io/dingodb/exec/OperatorFactory.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/AbstractParams.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/base/BaseTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/NoneTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/OptimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/PessimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/TransactionCache.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/CleanCacheOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/PessimisticResidualLockOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/params/PessimisticResidualLockParam.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/params/ScanCacheResidualLockParam.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/visitor/DingoTransactionRenderJob.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/visitor/Visitor.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/visitor/data/ElementName.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/visitor/data/PessimisticResidualLockLeaf.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/visitor/data/ScanCacheResidualLockLeaf.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/visitor/data/TransactionElements.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/visitor/function/DingoPessimisticResidualLockVisitFun.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/visitor/function/DingoScanCacheResidualLockVisitFun.java
dingo-exec/src/main/java/io/dingodb/exec/utils/OperatorCodeUtils.java
dingo-exec/src/test/java/io/dingodb/exec/impl/TestJobVisitor.java

[dingo-executor] Fix pessimistic transaction block issues

[dingo-executor] Fix pessimistic transaction block issues

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoParser.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/LoadDataOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/runtime/DingoResource.java
dingo-calcite/src/main/java/io/dingodb/calcite/utils/ParseValueUtils.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoGetByIndexMergeVisitFun.java
dingo-driver/host/src/main/resources/io/dingodb/calcite/runtime/DingoResource_en.properties

[fix][dingo-calcite] Load data add lock table

---

dingo-exec/src/main/java/io/dingodb/exec/transaction/base/BaseTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/PessimisticRollBackOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/params/PessimisticRollBackParam.java

[dingo-executor] Add transaction commit changed to synchronous

[dingo-executor] Add transaction commit changed to synchronous

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowLocksOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/TxnImportDataOperation.java
dingo-common/src/main/java/io/dingodb/common/CommonId.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartDeleteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/base/TxnLocalData.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/PessimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/TransactionCache.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/CleanCacheOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/CommitOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/PessimisticResidualLockOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/PessimisticRollBackOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/PreWriteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/RollBackOperator.java
dingo-exec/src/main/java/io/dingodb/exec/utils/ByteUtils.java

[dingo-executor] Optimize transaction local data encoding

[dingo-executor] Optimize transaction local data encoding

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoParser.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/LoadDataOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/TxnImportDataOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/runtime/DingoResource.java
dingo-common/src/main/java/io/dingodb/common/environment/ExecutionEnvironment.java

[fix][dingo-calcite] Load data rollback error

---

dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoTableModifyVisitFun.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoConnection.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockDeleteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartDeleteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/util/TransactionUtil.java
dingo-store-api/src/main/java/io/dingodb/store/api/transaction/exception/RegionSplitException.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/StoreService.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/TransactionStoreInstance.java

[dingo-executor] Optimize pessimistic transaction lock operator

[dingo-executor] Optimize pessimistic transaction lock operator

---

dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartUpdateOperator.java

[dingo-executor] Fix modify index primary key in transaction issue

[dingo-executor] Fix modify index primary key in transaction issue

---

dingo-calcite/src/main/codegen/includes/LoadData.ftl
dingo-calcite/src/main/codegen/templates/Parser.jj
dingo-calcite/src/main/java/io/dingodb/calcite/DingoParser.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/LoadDataOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/utils/ParseValueUtils.java
dingo-common/src/main/java/io/dingodb/common/util/Utils.java
dingo-exec/src/main/java/io/dingodb/exec/operator/ExportDataOperator.java

Load data terminated support multi bytes

[fix][dingo-calcite] Load data terminated support multi bytes

---

dingo-exec/src/main/java/io/dingodb/exec/transaction/base/BaseTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/OptimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/PessimisticTransaction.java

[dingo-executor] Fix cross node transaction error reporting issue

[dingo-executor] Fix cross node transaction error reporting issue

---

dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/base/BaseTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/PessimisticTransaction.java

[dingo-executor] Fix cross node transaction check continue issue

[dingo-executor] Fix cross node transaction check continue issue

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowCallsOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoVectorIndexRule.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoVectorJoinRule.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDdlVerify.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-exec/src/main/java/io/dingodb/exec/operator/ExportDataOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PartUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartUpdateOperator.java
dingo-executor/src/main/java/io/dingodb/server/executor/schedule/stats/TableModifyMonitorTask.java
dingo-web/src/main/java/io/dingodb/web/service/MonitorServerService.java

[fix][dingo-exec] Update index id error

---

dingo-common/src/main/java/io/dingodb/common/mysql/MysqlServer.java
dingo-web/src/main/java/io/dingodb/web/service/MonitorServerService.java

Modify web index partcols show

[fix][dingo-common] Delete mysql ssl

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/TxnImportDataOperation.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/ReduceOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/base/BaseTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/NoneTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/OptimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/PessimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/RollBackOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/params/RollBackParam.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/visitor/function/DingoRollBackVisitFun.java

[dingo-executor] Fix optimistic transaction retry issue

[dingo-executor] Fix optimistic transaction retry issue

---

dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlLoadData.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/LoadDataOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/runtime/DingoResource.java
dingo-calcite/src/main/java/io/dingodb/calcite/stats/StatsNormal.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoGetByIndexMergeVisitFun.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoGetByIndexVisitFun.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDdlVerify.java
dingo-driver/host/src/main/resources/io/dingodb/calcite/runtime/DingoResource_en.properties
dingo-exec/src/main/java/io/dingodb/exec/operator/ExportDataOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/TxnPartVectorParam.java
dingo-executor/src/main/java/io/dingodb/server/executor/schedule/stats/AnalyzeScanTask.java
dingo-executor/src/main/java/io/dingodb/server/executor/schedule/stats/TableModifyMonitorTask.java
dingo-proxy/src/main/java/io/dingodb/proxy/mapper/EntityMapper.java

Vector table data pushdown error

[fix][dingo-calcite] Vector table data pushdown error

---

docs/deployment/deploy_in_single_node_using_docker.md

[Docs] Fixed an issue with docker-compose configuration

---

dingo-common/src/main/java/io/dingodb/common/CommonId.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockDeleteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/base/BaseTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/TransactionCache.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/CleanCacheOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/PreWriteOperator.java
dingo-store-api/src/main/java/io/dingodb/store/api/transaction/data/Op.java

[dingo-executor] Add checkNotExists in optimistic transaction

[dingo-executor] Add checkNotExists in optimistic transaction

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/LoadDataOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/LockTableOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowProcessListOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/SqlToOperationConverter.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/TxnImportDataOperation.java
dingo-common/src/main/java/io/dingodb/common/ProcessInfo.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-exec/src/main/java/io/dingodb/exec/fun/vector/VectorCosineDistanceFun.java
dingo-exec/src/main/java/io/dingodb/exec/fun/vector/VectorIPDistanceFun.java
dingo-exec/src/main/java/io/dingodb/exec/fun/vector/VectorL2DistanceFun.java

1.Load file insert index
2.DINGODB-1665 vector search ArrayIndexOutOfBoundsException -1
3. DINGODB-1664  L2Distance, CosineDistance, IpDistance 目标向量和源向量维度校验/ 以及保留原始精度

[fix][dingo-calcite] Load file insert index

---

dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/RollBackOperator.java

[dingo-executor] Fix optimistic transaction rollback issue

[dingo-executor] Fix optimistic transaction rollback issue

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/LoadDataOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowTableDistributionOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/SqlToOperationConverter.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/TxnImportDataOperation.java

Improve performance for load data

[fix][dingo-calcite] Improve performance for load data

---

dingo-common/src/main/java/io/dingodb/common/util/DebugLog.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoSignature.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/OptimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/TransactionCache.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/PreWriteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/RollBackOperator.java

[dingo-executor] Add optimistic transaction autocommit sql retry

[dingo-executor] Add optimistic transaction autocommit sql retry

---

dingo-common/src/main/java/io/dingodb/common/vector/VectorSearchResponse.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartVectorOperator.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/StoreService.java

Transaction vector search use index vector

[fix][dingo-calcite] Transaction vector search use index vector

---

dingo-common/src/main/java/io/dingodb/common/CommonId.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/meta/MetaCache.java

Txnscan from local thread safety issues

[fix][dingo-common] Txnscan from local thread safety issues

---

dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockDeleteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartDeleteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/PessimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/PessimisticRollBackOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/util/TransactionUtil.java

[dingo-executor] Optimize pessimistic transaction lock and rollback

[dingo-executor] Optimize pessimistic transaction lock and rollback

---

dingo-calcite/src/main/java/io/dingodb/calcite/meta/DingoCostModelV1.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/TableLockService.java

[fix][dingo-calcite] Add lock log

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoSqlToRelConverter.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartVectorOperator.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/meta/MetaCache.java

[fix][dingo-calcite] Add log for solve the problem

---

dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlKill.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/KillConnection.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/KillQuery.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoScanProjectRule.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartVectorOperator.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/meta/MetaCache.java

当使用feature <-> array[xx] 时，暂时禁止使用后置过滤

[fix][dingo-calcite] Call distance fun transofrm to vector post filter without repExpr

---

dingo-store-proxy/src/main/java/io/dingodb/store/proxy/meta/MetaCache.java

Add log for resolve problem of Truncate/Drop error

[fix][dingo-calcite]  Add log for resolve problem of Truncate/Drop error

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/LoadDataOperation.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/SessionVariableChangeWatcher.java

[fix][dingo-calcite] Resolve OOM Problem of load data

---

dingo-dist/conf/executor.yaml
dingo-driver/client/src/main/java/io/dingodb/driver/DingoServiceImpl.java
dingo-store-local/src/main/java/io/dingodb/store/local/Configuration.java
dingo-store-local/src/main/java/io/dingodb/store/local/StoreService.java

[dingo-executor] Fix exception cast and rocksdb configuration issues

[dingo-executor] Fix exception cast and rocksdb configuration issues

---

dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoGetByIndexRule.java
dingo-exec/src/main/java/io/dingodb/exec/operator/CacheOpOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/CleanCacheOperator.java

1. 无主键表在应用索引规则时出错
2. groupby  并发错误修正
3. mysql prepare OOM

[fix][dingo-exec] Group fun Thread unsafe / mysql prepare OOM

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/LoadDataOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/TxnImportDataOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/rel/DingoGetByIndex.java
dingo-calcite/src/main/java/io/dingodb/calcite/rel/DingoGetByIndexMerge.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoGetByIndexRule.java

Load big infile cause region split

[fix][dingo-calcite] Load big infile cause region split

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowLocksOperation.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PessimisticLockOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartDeleteOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartUpdateOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/base/BaseTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/base/CacheToObject.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/OptimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/PessimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/TransactionCache.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/CleanCacheOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/util/TransactionUtil.java
dingo-store-local/src/main/java/io/dingodb/store/local/StoreService.java

[dingo-executor] Optimize high memory usage and retry issues

[dingo-executor] Optimize high memory usage and retry issues

---

docs/release_notes/dingodb_0_8_0_rn.md
docs/release_notes/index.rst

[docs] Add release notes about v0.8.0

[docs] Add release notes about v0.8.0

---

dingo-store-local/src/main/java/io/dingodb/store/local/StoreService.java

[dingo-executor] Fix local store default path issue

[dingo-executor] Fix local store default path issue

---

dingo-store-proxy/src/main/java/io/dingodb/store/proxy/meta/MetaCache.java

[fix][dingo-store-proxy] Fix get table null exception.

---

dingo-calcite/src/main/java/io/dingodb/calcite/rel/DingoGetByIndexMerge.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoGetByIndexRule.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoGetByIndexMergeVisitFun.java

IndexMerge run error without primary

[fix][dingo-calcite] IndexMerge run error without primary

---

dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoGetByIndexMergeVisitFun.java
dingo-common/src/main/java/io/dingodb/common/type/TupleMapping.java

Selection error during index merge deduplication

[fix][dingo-calcite] Selection error during index merge deduplication

---

dingo-exec/src/main/java/io/dingodb/exec/operator/GetDistributionOperator.java

[dingo-executor] Fix query using primary key equals null issue

[dingo-executor] Fix query using primary key equals null issue

---

dingo-net-netty/src/main/java/io/dingodb/net/netty/NetConfiguration.java

[fix][dingo-net-netty] Modify default api timeout

---

dingo-dist/conf/executor.yaml
dingo-store-local/src/main/java/io/dingodb/store/local/Configuration.java
dingo-store-local/src/main/java/io/dingodb/store/local/StoreInstance.java
dingo-store-local/src/main/java/io/dingodb/store/local/StoreService.java

[dingo-executor] Optimize local store parameters

[dingo-executor] Optimize local store parameters

---

gradle.properties

[dingo-release] bump release version to dingo-v0.8.0

[dingo-release] bump release version to dingo-v0.8.0

---

gradle.properties

[feat] Start a new version to v0.9.0

[feat] Start a new version to v0.9.0

---

gradle.properties

Fix vulnerability regarding logback in CVE-2021-42550

[fix][gradle] Fix vulnerability regarding logback in CVE-2021-42550

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowLocksOperation.java

Show locks NullPointerException

[fix][dingo-calcite] Show locks NullPointerException

---

dingo-common/src/main/java/io/dingodb/common/concurrent/Executors.java
dingo-executor/src/main/java/io/dingodb/server/executor/schedule/SafePointUpdateTask.java

[dingo-executor] Fix transaction gc safe point issue

[dingo-executor] Fix transaction gc safe point issue

---

dingo-executor/src/main/java/io/dingodb/server/executor/schedule/SafePointUpdateTask.java

[dingo-executor] Fix transaction gc set gc stop flag issue

[dingo-executor] Fix transaction gc set gc stop flag issue

---

dingo-calcite/src/main/java/io/dingodb/calcite/stats/Histogram.java
dingo-calcite/src/main/java/io/dingodb/calcite/visitor/function/DingoStreamingConverterVisitFun.java
dingo-common/src/main/java/io/dingodb/common/concurrent/Executors.java
dingo-common/src/main/java/io/dingodb/common/profile/OperatorProfile.java
dingo-common/src/main/java/io/dingodb/common/profile/Profile.java
dingo-common/src/main/java/io/dingodb/common/profile/SqlProfile.java
dingo-driver/client/src/main/java/io/dingodb/driver/client/DingoDriverClient.java
dingo-driver/host/src/main/java/io/dingodb/driver/ServerMeta.java
dingo-exec/src/main/java/io/dingodb/exec/fin/FinWithProfiles.java
dingo-exec/src/main/java/io/dingodb/exec/operator/HashJoinOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/ReceiveOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/HashJoinParam.java
dingo-exec/src/main/java/io/dingodb/exec/operator/params/ScanParam.java
dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/TableLockService.java

[fix][dingo-exec] Join statement profile block

---

dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/TransactionStoreInstance.java

[dingo-executor] Fix transaction lock time out issue

[dingo-executor] Fix transaction lock time out issue

---

dingo-common/src/main/java/io/dingodb/common/profile/ExecProfile.java
dingo-common/src/main/java/io/dingodb/common/profile/Profile.java
dingo-common/src/main/java/io/dingodb/common/profile/SqlProfile.java
dingo-common/src/main/java/io/dingodb/common/profile/StmtSummaryMap.java
dingo-dist/conf/logback-executor-release.xml
dingo-dist/conf/logback-executor.xml
dingo-driver/host/src/main/java/io/dingodb/driver/DingoConnection.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoSignature.java
dingo-exec/src/main/java/io/dingodb/exec/fin/FinWithProfiles.java
dingo-exec/src/main/java/io/dingodb/exec/operator/PartInsertOperator.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnPartInsertOperator.java
docker/templates/conf/logback-executor-release.xml
docker/templates/conf/logback-executor.xml

ExecutePrepare profile cause heap oom

[fix][dingo-common] ExecutePrepare profile cause heap oom

---

dingo-common/src/main/java/io/dingodb/common/concurrent/Executors.java
dingo-dist/conf/logback-executor-release.xml
dingo-dist/conf/logback-executor.xml
dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/base/BaseTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/PessimisticTransaction.java
dingo-executor/src/main/java/io/dingodb/server/executor/Starter.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/TableLockService.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/TransactionStoreInstance.java
docker/templates/conf/logback-executor-release.xml
docker/templates/conf/logback-executor.xml

[dingo-executor] Fix txn heartbeat schedule issue

[dingo-executor] Fix txn heartbeat schedule issue

---

gradle.properties

Modify netty version to 4.1.109.Final

[fix][gradle] Modify netty version to 4.1.109.Final

---

dingo-common/src/main/java/io/dingodb/common/metrics/LoggerReporter.java
dingo-common/src/main/java/io/dingodb/common/profile/OperatorProfile.java
dingo-common/src/main/java/io/dingodb/common/profile/SqlProfile.java
dingo-common/src/main/java/io/dingodb/common/profile/StmtSummary.java
dingo-exec/src/main/java/io/dingodb/exec/fin/FinWithProfiles.java
dingo-exec/src/main/java/io/dingodb/exec/operator/CoalesceOperator.java
dingo-exec/src/main/java/io/dingodb/exec/utils/RelOpUtils.java
dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java

[fix][dingo-common] Change replica to dynamic

---

dingo-calcite/src/main/codegen/config.fmpp
dingo-calcite/src/main/codegen/includes/parserImpls.ftl
dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/rule/DingoGetByIndexRule.java
dingo-calcite/src/main/java/org/apache/calcite/sql/ddl/DingoSqlKeyConstraint.java

[fix][dingo-calcite] Add unique index

---

dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/TableLockService.java

[dingo-executor] Fix lock table issue

[dingo-executor] Fix lock table issue

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/LoadDataOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowTableStatusOperation.java
dingo-dist/bin/fullbackup.sh
dingo-dist/bin/import-dump.sh
dingo-exec/src/main/java/io/dingodb/exec/operator/InfoSchemaScanOperator.java

[fix][dingo-calcite] Support full back

---

dingo-calcite/src/main/codegen/config.fmpp
dingo-calcite/src/main/codegen/includes/Grant.ftl
dingo-calcite/src/main/codegen/includes/Show.ftl
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/dql/SqlShowGrants.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/ShowGrantsOperation.java
dingo-calcite/src/main/java/io/dingodb/calcite/operation/SqlToOperationConverter.java
dingo-common/src/main/java/io/dingodb/common/privilege/DingoSqlAccessEnum.java
dingo-common/src/main/java/io/dingodb/common/privilege/PrivilegeDict.java
dingo-common/src/main/java/io/dingodb/common/privilege/PrivilegeList.java
dingo-common/src/main/java/io/dingodb/common/profile/SqlProfile.java
dingo-common/src/main/java/io/dingodb/common/profile/StmtSummary.java
dingo-common/src/main/java/io/dingodb/common/profile/StmtSummaryMap.java
dingo-dist/conf/application-web-dev.yaml
dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoPreparedStatement.java
dingo-exec/src/main/java/io/dingodb/exec/fin/FinWithProfiles.java
dingo-exec/src/main/java/io/dingodb/exec/operator/CoalesceOperator.java
dingo-executor/src/main/java/io/dingodb/server/executor/service/UserService.java
dingo-mysql-init/src/main/resources/information-stmtSummary.json
dingo-mysql-init/src/main/resources/mysql-user.json
dingo-web/src/main/java/io/dingodb/web/bean/LogEventCache.java
dingo-web/src/main/java/io/dingodb/web/bean/MonitorBean.java
dingo-web/src/main/java/io/dingodb/web/controller/MonitorController.java
dingo-web/src/main/java/io/dingodb/web/model/dto/Stmt.java
dingo-web/src/main/java/io/dingodb/web/model/vo/ResVo.java
dingo-web/src/main/java/io/dingodb/web/service/DaoService.java
dingo-web/src/main/java/io/dingodb/web/service/MonitorServerService.java
dingo-web/src/main/resources/config/application.yaml

[fix][dingo-calcite] Add monitor login

---

dingo-calcite/src/main/java/io/dingodb/calcite/operation/VariableValidator.java
dingo-common/src/main/java/io/dingodb/common/audit/DingoAudit.java
dingo-common/src/main/java/io/dingodb/common/audit/IAudit.java
dingo-common/src/main/java/io/dingodb/common/log/AuditLogUtils.java
dingo-common/src/main/java/io/dingodb/common/log/BackUpLogUtils.java
dingo-dist/conf/logback-executor-release.xml
dingo-dist/conf/logback-executor.xml
dingo-driver/host/src/main/java/io/dingodb/driver/DingoDriverParser.java
dingo-driver/host/src/main/java/io/dingodb/driver/DingoMeta.java
dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
docker/templates/conf/logback-executor-release.xml
docker/templates/conf/logback-executor.xml

[dingo-executor] Add audit log and incremental backup features

[dingo-executor] Add audit log and incremental backup features

---

dingo-calcite/src/main/codegen/includes/parserImpls.ftl
dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-calcite/src/main/java/io/dingodb/calcite/grammar/ddl/SqlCreateUser.java
dingo-common/src/main/java/io/dingodb/common/config/LdapConfiguration.java
dingo-common/src/main/java/io/dingodb/common/config/SecurityConfiguration.java
dingo-common/src/main/java/io/dingodb/common/privilege/UserDefinition.java
dingo-dist/conf/executor.yaml
dingo-driver/mysql-service/build.gradle
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/netty/HandshakeHandler.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/netty/LdapConn.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/packet/AuthPacket.java
dingo-exec/src/main/java/io/dingodb/exec/operator/SortOperator.java
dingo-executor/src/main/java/io/dingodb/server/executor/service/UserService.java
dingo-mysql-init/src/main/resources/mysql-user.json
dingo-verify/src/main/java/io/dingodb/verify/plugin/AlgorithmPlugin.java
docker/templates/conf/executor.yaml

[fix][dingo-calcite] Support ldap

---

dingo-calcite/src/main/java/io/dingodb/calcite/DingoDdlExecutor.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/base/BaseTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/impl/PessimisticTransaction.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/CommitOperator.java
dingo-exec/src/main/java/io/dingodb/exec/transaction/operator/RollBackOperator.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/TableLockService.java
dingo-store-proxy/src/main/java/io/dingodb/store/proxy/service/TransactionStoreInstance.java

[dingo-executor] Fix transaction rollback and checkNotExists issues

[dingo-executor] Fix transaction rollback and checkNotExists issues

---

dingo-common/src/main/java/io/dingodb/common/restful/RestfulClient.java
dingo-driver/mysql-service/src/main/java/io/dingodb/driver/mysql/netty/LdapConn.java
dingo-exec/src/main/java/io/dingodb/exec/operator/TxnGetByIndexOperator.java

[fix][dingo-common] Txt2Vec fun load error
